import { hexFromArgb } from '@material/material-color-utilities';
function hexToArgbSigned(hex) {
  const h = hex.replace('#', '');
  const r = parseInt(h.substring(0, 2), 16);
  const g = parseInt(h.substring(2, 4), 16);
  const b = parseInt(h.substring(4, 6), 16);
  let val = (0xFF << 24) | (r << 16) | (g << 8) | b;
  if (val > 0x7FFFFFFF) val = val - 0x100000000;
  return val;
}
function argbToSigned(argb) {
  return hexToArgbSigned(hexFromArgb(argb));
}
export function generateMobileTheme(scheme, isDark = false) {
  const s = scheme;
  const p = (token) => argbToSigned(token);
  const safeScheme = {
    ...s,
    surfaceContainerLow: s.surfaceContainerLow ?? s.surfaceVariant,
    surfaceContainer:    s.surfaceContainer    ?? s.surfaceVariant,
    surfaceContainerHigh:s.surfaceContainerHigh?? s.surfaceVariant,
    primaryFixed:        s.primaryFixed        ?? s.primaryContainer,
  };
  const ss = safeScheme;
  const H = {
    'avatar_actionBarSelectorGreen': hexToArgbSigned('#879488'),
    'avatar_background2Blue': isDark ? hexToArgbSigned('#434652') : hexToArgbSigned('#E0E2F1'),
    'avatar_background2Cyan': isDark ? hexToArgbSigned('#3B494B') : hexToArgbSigned('#E4F4F6'),
    'avatar_background2Green': isDark ? hexToArgbSigned('#3E4A40') : hexToArgbSigned('#E7F4E7'),
    'avatar_background2Pink': isDark ? hexToArgbSigned('#51434C') : hexToArgbSigned('#F2DDE9'),
    'avatar_background2Red': isDark ? hexToArgbSigned('#564244') : hexToArgbSigned('#F9DBDE'),
    'avatar_background2Violet': isDark ? hexToArgbSigned('#4D4450') : hexToArgbSigned('#ECDEEE'),
    'avatar_backgroundBlue': isDark ? hexToArgbSigned('#434652') : hexToArgbSigned('#E0E2F1'),
    'avatar_backgroundCyan': isDark ? hexToArgbSigned('#3B494B') : hexToArgbSigned('#E4F4F6'),
    'avatar_backgroundGreen': isDark ? hexToArgbSigned('#3E4A40') : hexToArgbSigned('#E7F4E7'),
    'avatar_backgroundInProfileBlue': isDark ? hexToArgbSigned('#434652') : hexToArgbSigned('#E0E2F1'),
    'avatar_backgroundPink': isDark ? hexToArgbSigned('#51434C') : hexToArgbSigned('#F2DDE9'),
    'avatar_backgroundRed': isDark ? hexToArgbSigned('#564244') : hexToArgbSigned('#F9DBDE'),
    'avatar_backgroundViolet': isDark ? hexToArgbSigned('#4D4450') : hexToArgbSigned('#ECDEEE'),
    'avatar_nameInMessageBlue': isDark ? hexToArgbSigned('#C4C6D4') : hexToArgbSigned('#747684'),
    'avatar_nameInMessageCyan': isDark ? hexToArgbSigned('#BAC9CB') : hexToArgbSigned('#6B7A7C'),
    'avatar_nameInMessageGreen': isDark ? hexToArgbSigned('#BDCABD') : hexToArgbSigned('#6E7A6F'),
    'avatar_nameInMessageOrange': isDark ? hexToArgbSigned('#D1C5AE') : hexToArgbSigned('#807662'),
    'avatar_nameInMessagePink': isDark ? hexToArgbSigned('#D5C1CD') : hexToArgbSigned('#83727D'),
    'avatar_nameInMessageRed': isDark ? hexToArgbSigned('#DCC0C2') : hexToArgbSigned('#897173'),
    'avatar_nameInMessageViolet': isDark ? hexToArgbSigned('#CFC2D2') : hexToArgbSigned('#7E7481'),
    'calls_callReceivedGreenIcon': isDark ? hexToArgbSigned('#879488') : hexToArgbSigned('#6E7A6F'),
    'chat_inPollCorrectAnswer': hexToArgbSigned('#879488'),
    'chat_messagePanelHint': hexToArgbSigned('#899295'),
    'chat_outPollCorrectAnswer': isDark ? hexToArgbSigned('#3E4A40') : hexToArgbSigned('#556157'),
    'chat_recordedVoiceDot': isDark ? hexToArgbSigned('#F2B8B5') : hexToArgbSigned('#A48B8D'),
    'chat_reportSpam': isDark ? hexToArgbSigned('#BCC5EB') : hexToArgbSigned('#111A37'),
    'chat_serviceBackground': isDark ? hexToArgbSigned('#334A50') : hexToArgbSigned('#E9F2F5'),
    'chat_serviceBackgroundSelected': isDark ? hexToArgbSigned('#334A50') : hexToArgbSigned('#F7FDFF'),
    'chats_archivePullDownBackground': isDark ? hexToArgbSigned('#1C3439') : hexToArgbSigned('#899295'),
    'chats_archivePullDownBackgroundActive': isDark ? hexToArgbSigned('#303031') : hexToArgbSigned('#A3ADAF'),
    'chats_secretIcon': isDark ? hexToArgbSigned('#BDCABD') : hexToArgbSigned('#556157'),
    'chats_secretName': isDark ? hexToArgbSigned('#BDCABD') : hexToArgbSigned('#556157'),
    'chats_verifiedCheck': isDark ? hexToArgbSigned('#00363E') : hexToArgbSigned('-1'),
    'code_background': isDark ? hexToArgbSigned('#000000') : hexToArgbSigned('#E3E2E2'),
    'code_constannt': isDark ? hexToArgbSigned('#8E909E') : hexToArgbSigned('#747684'),
    'code_constant': isDark ? hexToArgbSigned('#8E909E') : hexToArgbSigned('#5B5E6A'),
    'code_function': isDark ? hexToArgbSigned('#988D9B') : hexToArgbSigned('#7E7481'),
    'code_inBackground': isDark ? hexToArgbSigned('#464747') : hexToArgbSigned('#E3E2E2'),
    'code_keyword': isDark ? hexToArgbSigned('#7C959B') : hexToArgbSigned('#6B7A7C'),
    'code_number': isDark ? hexToArgbSigned('#9E8C97') : hexToArgbSigned('#83727D'),
    'code_operator': isDark ? hexToArgbSigned('#9A907A') : hexToArgbSigned('#807662'),
    'code_string': isDark ? hexToArgbSigned('#879488') : hexToArgbSigned('#6E7A6F'),
    'color_blue': hexToArgbSigned('#747684'),
    'color_cyan': hexToArgbSigned('#6B7A7C'),
    'color_green': hexToArgbSigned('#6E7A6F'),
    'color_lightblue': hexToArgbSigned('#A8AAB9'),
    'color_lightgreen': hexToArgbSigned('#A2AFA2'),
    'color_orange': hexToArgbSigned('#807662'),
    'color_purple': isDark ? hexToArgbSigned('#9E8C97') : hexToArgbSigned('#83727D'),
    'color_red': isDark ? hexToArgbSigned('#A48B8D') : hexToArgbSigned('#897173'),
    'color_yellow': hexToArgbSigned('#9A907A'),
    'groupcreate_sectionShadow': isDark ? hexToArgbSigned('-1') : hexToArgbSigned('0'),
    'groupcreate_spanText': isDark ? hexToArgbSigned('#0E1416') : hexToArgbSigned('-1'),
    'key_chat_recordedVoiceHighlight': hexToArgbSigned('#6E787A'),
    'location_sendLiveLocationIcon': isDark ? hexToArgbSigned('#00363E') : hexToArgbSigned('-1'),
    'picker_badge': isDark ? hexToArgbSigned('#DEE3E5') : hexToArgbSigned('-1'),
    'premiumGradient0': isDark ? hexToArgbSigned('#6B7A7C') : hexToArgbSigned('#849395'),
    'premiumGradient1': isDark ? hexToArgbSigned('#747684') : hexToArgbSigned('#8E909E'),
    'premiumGradient2': isDark ? hexToArgbSigned('#7E7481') : hexToArgbSigned('#988D9B'),
    'premiumGradient3': isDark ? hexToArgbSigned('#83727D') : hexToArgbSigned('#9E8C97'),
    'premiumGradient4': isDark ? hexToArgbSigned('#655B68') : hexToArgbSigned('#988D9B'),
    'premiumGradientBackground1': isDark ? hexToArgbSigned('#51434C') : hexToArgbSigned('#BAC9CB'),
    'premiumGradientBackground2': isDark ? hexToArgbSigned('#655B68') : hexToArgbSigned('#A8AAB9'),
    'premiumGradientBackground3': isDark ? hexToArgbSigned('#5B5E6A') : hexToArgbSigned('#B3A7B6'),
    'premiumGradientBackground4': isDark ? hexToArgbSigned('#3B494B') : hexToArgbSigned('#B9A6B1'),
    'premiumGradientBackgroundOverlay': isDark ? hexToArgbSigned('#FEFBFF') : hexToArgbSigned('#181B26'),
    'premiumGradientBottomSheet1': isDark ? hexToArgbSigned('#5B5E6A') : hexToArgbSigned('#C4C6D4'),
    'premiumGradientBottomSheet2': isDark ? hexToArgbSigned('#655B68') : hexToArgbSigned('#CFC2D2'),
    'premiumGradientBottomSheet3': isDark ? hexToArgbSigned('#6A5A64') : hexToArgbSigned('#D5C1CD'),
    'premiumStarGradient1': hexToArgbSigned('#EEF0FF'),
    'premiumStarGradient2': hexToArgbSigned('#FAECFC'),
    'premiumStartGradient1': hexToArgbSigned('#747684'),
    'premiumStartGradient2': hexToArgbSigned('#7E7481'),
    'premiumStartSmallStarsColor': isDark ? hexToArgbSigned('#E0E2F1') : hexToArgbSigned('#EEF0FF'),
    'premiumStartSmallStarsColor2': isDark ? hexToArgbSigned('#ECDEEE') : hexToArgbSigned('#FAECFC'),
    'profile_verifiedCheck': isDark ? hexToArgbSigned('#00363E') : hexToArgbSigned('-1'),
    'statisticChartLineEmpty': isDark ? hexToArgbSigned('#303031') : hexToArgbSigned('-1'),
    'statisticChartLine_blue': hexToArgbSigned('#8E909E'),
    'statisticChartLine_cyan': hexToArgbSigned('#849395'),
    'statisticChartLine_golden': hexToArgbSigned('#9A907A'),
    'statisticChartLine_green': hexToArgbSigned('#879488'),
    'statisticChartLine_indigo': hexToArgbSigned('#988D9B'),
    'statisticChartLine_lightgreen': hexToArgbSigned('#7C959B'),
    'statisticChartLine_orange': isDark ? hexToArgbSigned('#899295') : hexToArgbSigned('#919191'),
    'statisticChartLine_purple': hexToArgbSigned('#9E8C97'),
    'statisticChartLine_red': hexToArgbSigned('#A48B8D'),
    'stories_circle_closeFriends1': hexToArgbSigned('#6E7A6F'),
    'stories_circle_closeFriends2': hexToArgbSigned('#6E7A6F'),
    'voipgroup_leaveButton': hexToArgbSigned('#97AFB6'),
    'voipgroup_listeningText': hexToArgbSigned('#A3ADAF'),
    'voipgroup_muteButton2': hexToArgbSigned('#A3ADAF'),
    'voipgroup_mutedByAdminGradient3': isDark ? hexToArgbSigned('#7C959B') : hexToArgbSigned('#97AFB6'),
    'voipgroup_mutedByAdminIcon': hexToArgbSigned('#7C959B'),
    'voipgroup_mutedByAdminMuteButton': hexToArgbSigned('#97AFB6'),
    'voipgroup_mutedIcon': hexToArgbSigned('#899295'),
    'voipgroup_mutedIconUnscrolled': hexToArgbSigned('#899295'),
    'voipgroup_overlayAlertGradientMuted': hexToArgbSigned('#899295'),
    'voipgroup_overlayAlertMutedByAdmin': hexToArgbSigned('#97AFB6'),
    'voipgroup_overlayBlue1': hexToArgbSigned('#899295'),
    'voipgroup_soundButton': hexToArgbSigned('#7C959B'),
    'voipgroup_soundButtonActive': hexToArgbSigned('#7C959B'),
    'voipgroup_soundButtonActiveScrolled': hexToArgbSigned('#7C959B'),
    'voipgroup_unmuteButton2': isDark ? hexToArgbSigned('#B2CBD1') : hexToArgbSigned('#6E787A'),
    'wallet_greenText': isDark ? hexToArgbSigned('#6E7A6F') : hexToArgbSigned('#556157'),
    'windowBackgroundWhiteGreenText': isDark ? hexToArgbSigned('#BDCABD') : hexToArgbSigned('#556157'),
    'windowBackgroundWhiteGreenText2': isDark ? hexToArgbSigned('#BDCABD') : hexToArgbSigned('#556157'),
  };
  const tokens = {
    'actionBarActionModeDefault': p(ss.surfaceContainer),
    'actionBarActionModeDefaultIcon': p(s.onSurfaceVariant),
    'actionBarActionModeDefaultSelector': p(ss.surfaceContainer),
    'actionBarActionModeDefaultTop': p(s.onSurfaceVariant),
    'actionBarActionModeReaction': p(s.error),
    'actionBarActionModeReactionDot': p(s.onErrorContainer),
    'actionBarActionModeReactionText': p(s.error),
    'actionBarBrowser': p(ss.surfaceContainer),
    'actionBarDefault': p(ss.surfaceContainer),
    'actionBarDefaultArchived': p(ss.surfaceContainer),
    'actionBarDefaultArchivedIcon': p(s.onSurfaceVariant),
    'actionBarDefaultArchivedSearch': p(s.primaryContainer),
    'actionBarDefaultArchivedSearchPlaceholder': p(s.outlineVariant),
    'actionBarDefaultArchivedSelector': p(s.onSurfaceVariant),
    'actionBarDefaultArchivedTitle': p(s.onSurfaceVariant),
    'actionBarDefaultIcon': p(s.onSurfaceVariant),
    'actionBarDefaultSearch': p(s.onSurfaceVariant),
    'actionBarDefaultSearchArchivedPlaceholder': p(ss.surfaceContainer),
    'actionBarDefaultSearchPlaceholder': p(s.primary),
    'actionBarDefaultSelector': p(s.onSurfaceVariant),
    'actionBarDefaultSubmenuBackground': p(ss.surfaceContainer),
    'actionBarDefaultSubmenuItem': p(s.onSurfaceVariant),
    'actionBarDefaultSubmenuItemIcon': p(s.onSurfaceVariant),
    'actionBarDefaultSubmenuSeparator': p(ss.surfaceContainer),
    'actionBarDefaultSubtitle': p(s.onSurfaceVariant),
    'actionBarDefaultTitle': p(s.onSurface),
    'actionBarTabActiveText': p(s.primary),
    'actionBarTabLine': p(s.primary),
    'actionBarTabSelector': p(s.primary),
    'actionBarTabUnactiveText': p(s.onSurfaceVariant),
    'actionBarTipBackground': p(ss.surfaceContainer),
    'actionBarWhiteSelector': p(s.onSurfaceVariant),
    'avatar_actionBarIconBlue': p(s.onSurfaceVariant),
    'avatar_actionBarSelectorBlue': p(s.outline),
    'avatar_actionBarSelectorGreen': H['avatar_actionBarSelectorGreen'],
    'avatar_background2Blue': H['avatar_background2Blue'],
    'avatar_background2Cyan': H['avatar_background2Cyan'],
    'avatar_background2Green': H['avatar_background2Green'],
    'avatar_background2Orange': p(s.secondaryContainer),
    'avatar_background2Pink': H['avatar_background2Pink'],
    'avatar_background2Red': H['avatar_background2Red'],
    'avatar_background2Saved': p(s.secondaryContainer),
    'avatar_background2Violet': H['avatar_background2Violet'],
    'avatar_backgroundActionBarBlue': p(ss.surfaceContainer),
    'avatar_backgroundArchived': p(ss.surfaceContainerLow),
    'avatar_backgroundArchivedHidden': p(ss.surfaceContainerLow),
    'avatar_backgroundBlue': H['avatar_backgroundBlue'],
    'avatar_backgroundCyan': H['avatar_backgroundCyan'],
    'avatar_backgroundGray': p(s.outlineVariant),
    'avatar_backgroundGreen': H['avatar_backgroundGreen'],
    'avatar_backgroundInProfileBlue': H['avatar_backgroundInProfileBlue'],
    'avatar_backgroundOrange': p(s.secondaryContainer),
    'avatar_backgroundPink': H['avatar_backgroundPink'],
    'avatar_backgroundRed': H['avatar_backgroundRed'],
    'avatar_backgroundSaved': p(s.secondaryContainer),
    'avatar_backgroundViolet': H['avatar_backgroundViolet'],
    'avatar_nameInMessageBlue': H['avatar_nameInMessageBlue'],
    'avatar_nameInMessageCyan': H['avatar_nameInMessageCyan'],
    'avatar_nameInMessageGreen': H['avatar_nameInMessageGreen'],
    'avatar_nameInMessageOrange': H['avatar_nameInMessageOrange'],
    'avatar_nameInMessagePink': H['avatar_nameInMessagePink'],
    'avatar_nameInMessageRed': H['avatar_nameInMessageRed'],
    'avatar_nameInMessageViolet': H['avatar_nameInMessageViolet'],
    'avatar_subtitleInProfileBlue': p(s.onSurfaceVariant),
    'avatar_text': p(s.onSurface),
    'bot_loadingIcon': p(s.onSurfaceVariant),
    'calls_callReceivedGreenIcon': H['calls_callReceivedGreenIcon'],
    'calls_callReceivedRedIcon': p(s.error),
    'changephoneinfo_image': p(s.primary),
    'changephoneinfo_image2': p(s.primary),
    'chat_BlurAlpha': p(s.background),
    'chat_BlurAlphaSlow': p(s.error),
    'chat_TextSelectionCursor': p(s.primary),
    'chat_addContact': p(s.primary),
    'chat_adminSelectedText': p(s.outlineVariant),
    'chat_adminText': p(s.outlineVariant),
    'chat_attachActiveTab': p(s.secondaryContainer),
    'chat_attachAudioBackground': p(s.primaryContainer),
    'chat_attachAudioIcon': p(s.primaryContainer),
    'chat_attachAudioText': p(s.onSurface),
    'chat_attachCheckBoxBackground': p(s.primary),
    'chat_attachCheckBoxCheck': p(ss.surfaceContainerLow),
    'chat_attachContactBackground': p(s.primaryContainer),
    'chat_attachContactIcon': p(s.onPrimary),
    'chat_attachContactText': p(s.onSurface),
    'chat_attachEmptyImage': p(s.primary),
    'chat_attachFileBackground': p(s.primaryContainer),
    'chat_attachFileIcon': p(s.onPrimary),
    'chat_attachFileText': p(s.onSurface),
    'chat_attachGalleryBackground': p(s.primaryContainer),
    'chat_attachGalleryIcon': p(s.onPrimary),
    'chat_attachGalleryText': p(s.onSurface),
    'chat_attachIcon': p(s.onPrimary),
    'chat_attachLocationBackground': p(s.primaryContainer),
    'chat_attachLocationIcon': p(s.onPrimary),
    'chat_attachLocationText': p(s.onSurface),
    'chat_attachMediaBanBackground': p(s.background),
    'chat_attachMediaBanText': p(s.onSurface),
    'chat_attachPermissionImage': p(s.outline),
    'chat_attachPermissionMark': p(s.onSurface),
    'chat_attachPermissionText': p(s.primary),
    'chat_attachPhotoBackground': p(s.primaryContainer),
    'chat_attachPollBackground': p(s.primaryContainer),
    'chat_attachPollIcon': p(s.onPrimary),
    'chat_attachPollText': p(s.onSurface),
    'chat_attachUnactiveTab': p(s.outlineVariant),
    'chat_botButtonText': p(s.onPrimary),
    'chat_botKeyboardButtonBackground': p(s.background),
    'chat_botKeyboardButtonBackgroundPressed': p(s.outlineVariant),
    'chat_botKeyboardButtonText': p(s.onPrimary),
    'chat_botProgress': p(ss.surfaceContainerLow),
    'chat_botSwitchToInlineText': p(ss.surfaceContainerHigh),
    'chat_editMediaButton': p(s.primaryContainer),
    'chat_emojiBottomPanelIcon': p(s.background),
    'chat_emojiPanelBackground': p(ss.surfaceContainer),
    'chat_emojiPanelBackspace': p(s.onSurfaceVariant),
    'chat_emojiPanelBadgeBackground': p(s.background),
    'chat_emojiPanelBadgeText': p(s.onSurface),
    'chat_emojiPanelEmptyText': p(s.onSurfaceVariant),
    'chat_emojiPanelIcon': p(s.onSurfaceVariant),
    'chat_emojiPanelIconSelected': p(s.primary),
    'chat_emojiPanelIconSelector': p(s.primary),
    'chat_emojiPanelMasksIcon': p(s.primary),
    'chat_emojiPanelMasksIconSelected': p(s.onSurfaceVariant),
    'chat_emojiPanelNewTrending': p(s.primary),
    'chat_emojiPanelShadowLine': 0,
    'chat_emojiPanelStickerPackSelector': p(s.onPrimaryContainer),
    'chat_emojiPanelStickerPackSelectorLine': p(s.primary),
    'chat_emojiPanelStickerSetName': p(s.primary),
    'chat_emojiPanelStickerSetNameHighlight': p(ss.surfaceContainerHigh),
    'chat_emojiPanelStickerSetNameIcon': p(s.primary),
    'chat_emojiPanelTrendingDescription': p(s.primary),
    'chat_emojiPanelTrendingTitle': p(s.primary),
    'chat_emojiSearchBackground': p(s.inverseOnSurface),
    'chat_emojiSearchIcon': p(s.onSurfaceVariant),
    'chat_fieldOverlayText': p(s.onSurface),
    'chat_gifSaveHintBackground': p(s.outline),
    'chat_gifSaveHintText': p(ss.surfaceContainerHigh),
    'chat_goDownButton': p(s.primaryContainer),
    'chat_goDownButtonCounter': p(s.inverseSurface),
    'chat_goDownButtonCounterBackground': p(s.primaryContainer),
    'chat_goDownButtonIcon': p(s.inverseSurface),
    'chat_goDownButtonShadow': p(s.onSurface),
    'chat_inAdminSelectedText': p(s.onSurfaceVariant),
    'chat_inAdminText': p(s.onSurfaceVariant),
    'chat_inAudioCacheSeekbar': p(s.onSurfaceVariant),
    'chat_inAudioDurationSelectedText': p(s.onSurface),
    'chat_inAudioDurationText': p(s.onSurfaceVariant),
    'chat_inAudioPerfomerSelectedText': p(s.onSurface),
    'chat_inAudioPerfomerText': p(s.onSurface),
    'chat_inAudioProgress': p(s.onSurface),
    'chat_inAudioSeekbar': p(s.outlineVariant),
    'chat_inAudioSeekbarFill': p(s.onSurface),
    'chat_inAudioSeekbarSelected': p(s.onSurface),
    'chat_inAudioSelectedProgress': p(s.outlineVariant),
    'chat_inAudioTitleText': p(s.onSurface),
    'chat_inBubble': p(ss.surfaceContainerHigh),
    'chat_inBubbleLocationPlaceholder': p(s.inverseSurface),
    'chat_inBubbleSelected': p(ss.surfaceContainerHigh),
    'chat_inBubbleShadow': 0,
    'chat_inCodeBackground': p(s.onSurfaceVariant),
    'chat_inContactBackground': p(s.primary),
    'chat_inContactIcon': p(s.primary),
    'chat_inContactNameText': p(s.onSurface),
    'chat_inContactPhoneSelectedText': p(ss.surfaceContainerHigh),
    'chat_inContactPhoneText': p(s.onSurface),
    'chat_inDownCall': p(s.primary),
    'chat_inFileBackground': p(s.onSurface),
    'chat_inFileBackgroundSelected': p(s.onSurface),
    'chat_inFileIcon': p(ss.surfaceContainerHigh),
    'chat_inFileInfoSelectedText': p(s.onSurfaceVariant),
    'chat_inFileInfoText': p(s.onSurfaceVariant),
    'chat_inFileNameText': p(s.onSurface),
    'chat_inFileProgress': p(s.onSurface),
    'chat_inFileProgressSelected': p(s.onSurface),
    'chat_inFileSelectedIcon': p(s.secondaryContainer),
    'chat_inForwardedNameText': p(s.onSurfaceVariant),
    'chat_inGreenCall': p(ss.surfaceContainerLow),
    'chat_inInstant': p(s.onSurface),
    'chat_inInstantSelected': p(s.onSurface),
    'chat_inLoader': p(s.primaryContainer),
    'chat_inLoaderPhoto': p(s.primaryContainer),
    'chat_inLoaderPhotoIcon': p(s.onPrimary),
    'chat_inLoaderPhotoIconSelected': p(s.onPrimary),
    'chat_inLoaderPhotoSelected': p(s.primaryContainer),
    'chat_inLoaderSelected': p(s.primaryContainer),
    'chat_inLocationBackground': p(s.inverseOnSurface),
    'chat_inLocationIcon': p(s.onSurface),
    'chat_inMediaIcon': p(s.onPrimary),
    'chat_inMediaIconSelected': p(s.onPrimary),
    'chat_inMenu': 0,
    'chat_inMenuSelected': 0,
    'chat_inPollCorrectAnswer': H['chat_inPollCorrectAnswer'],
    'chat_inPollWrongAnswer': p(s.error),
    'chat_inPreviewInstantSelectedText': p(s.onSurface),
    'chat_inPreviewInstantText': p(s.onSurface),
    'chat_inPreviewLine': p(s.outlineVariant),
    'chat_inPsaNameText': p(s.onSurface),
    'chat_inQuote': p(s.onErrorContainer),
    'chat_inReactionButtonBackground': p(s.primary),
    'chat_inReactionButtonText': p(s.onSurface),
    'chat_inReactionButtonTextSelected': p(ss.surfaceContainerLow),
    'chat_inRedCall': -1,
    'chat_inReplyLine': p(s.onSurfaceVariant),
    'chat_inReplyMediaMessageSelectedText': p(s.onSurfaceVariant),
    'chat_inReplyMediaMessageText': p(s.onSurfaceVariant),
    'chat_inReplyMessageText': p(s.onSurfaceVariant),
    'chat_inReplyNameText': p(s.onSurfaceVariant),
    'chat_inSentClock': p(s.onSurfaceVariant),
    'chat_inSentClockSelected': p(s.onSurfaceVariant),
    'chat_inSiteNameText': p(s.onSurfaceVariant),
    'chat_inTextSelectionHighlight': p(s.outlineVariant),
    'chat_inTimeSelectedText': p(s.onSurfaceVariant),
    'chat_inTimeText': p(s.onSurfaceVariant),
    'chat_inUpCall': -1,
    'chat_inVenueInfoSelectedText': p(s.onSurfaceVariant),
    'chat_inVenueInfoText': p(s.onSurface),
    'chat_inViaBotNameText': p(s.tertiary),
    'chat_inViews': p(s.onSurfaceVariant),
    'chat_inViewsSelected': p(s.onSurfaceVariant),
    'chat_inVoiceSeekbar': p(s.outlineVariant),
    'chat_inVoiceSeekbarFill': p(s.onSurface),
    'chat_inVoiceSeekbarSelected': p(s.outlineVariant),
    'chat_inlineResultIcon': p(s.primary),
    'chat_linkSelectBackground': p(s.tertiaryContainer),
    'chat_lockIcon': p(s.primary),
    'chat_mediaInfoText': p(s.onPrimaryContainer),
    'chat_mediaLoaderPhoto': p(s.primaryContainer),
    'chat_mediaLoaderPhotoIcon': p(s.onPrimary),
    'chat_mediaLoaderPhotoIconSelected': p(s.onPrimary),
    'chat_mediaLoaderPhotoSelected': p(s.primaryContainer),
    'chat_mediaMenu': p(s.primaryContainer),
    'chat_mediaProgress': p(s.primary),
    'chat_mediaSentCheck': p(s.onPrimary),
    'chat_mediaSentClock': p(s.onPrimary),
    'chat_mediaTimeBackground': p(s.primaryContainer),
    'chat_mediaTimeText': p(s.onPrimary),
    'chat_mediaViews': p(s.onPrimary),
    'chat_messageLinkIn': p(s.tertiary),
    'chat_messageLinkOut': p(s.tertiary),
    'chat_messagePanelBackground': p(ss.surfaceContainer),
    'chat_messagePanelCancelInlineBot': p(s.primary),
    'chat_messagePanelCursor': p(s.primary),
    'chat_messagePanelHint': H['chat_messagePanelHint'],
    'chat_messagePanelIcons': p(s.onSurface),
    'chat_messagePanelSend': p(s.primary),
    'chat_messagePanelShadow': 0,
    'chat_messagePanelText': p(s.onSurface),
    'chat_messagePanelVideoFrame': p(s.outline),
    'chat_messagePanelVoiceBackground': p(ss.surfaceContainerHigh),
    'chat_messagePanelVoiceDelete': p(s.error),
    'chat_messagePanelVoiceDuration': p(s.onSurfaceVariant),
    'chat_messagePanelVoiceLock': p(s.onPrimaryContainer),
    'chat_messagePanelVoiceLockBackground': p(s.onPrimaryContainer),
    'chat_messagePanelVoiceLockShadow': p(s.onSurface),
    'chat_messagePanelVoicePressed': p(s.onPrimaryContainer),
    'chat_messageTextIn': p(s.onSurface),
    'chat_messageTextOut': p(s.inverseSurface),
    'chat_muteIcon': p(s.onSurfaceVariant),
    'chat_outAdminSelectedText': p(s.inverseSurface),
    'chat_outAdminText': p(s.inverseSurface),
    'chat_outAudioCacheSeekbar': p(s.onSurfaceVariant),
    'chat_outAudioDurationSelectedText': p(s.secondary),
    'chat_outAudioDurationText': p(s.secondary),
    'chat_outAudioPerfomerSelectedText': p(s.secondary),
    'chat_outAudioPerfomerText': p(s.secondary),
    'chat_outAudioProgress': p(s.onPrimaryContainer),
    'chat_outAudioSeekbar': p(s.onSurfaceVariant),
    'chat_outAudioSeekbarFill': p(s.onPrimaryContainer),
    'chat_outAudioSeekbarSelected': p(s.onPrimaryContainer),
    'chat_outAudioSelectedProgress': p(s.secondaryContainer),
    'chat_outAudioTitleText': p(s.onPrimaryContainer),
    'chat_outBubble': p(s.secondaryContainer),
    'chat_outBubbleGradient': p(s.secondaryContainer),
    'chat_outBubbleGradient2': p(s.secondaryContainer),
    'chat_outBubbleGradient3': p(s.secondaryContainer),
    'chat_outBubbleGradientAnimated': p(s.secondaryContainer),
    'chat_outBubbleGradientSelectedOverlay': p(s.secondaryContainer),
    'chat_outBubbleLocationPlaceholder': p(s.inverseSurface),
    'chat_outBubbleSelected': p(s.secondaryContainer),
    'chat_outBubbleShadow': 0,
    'chat_outCodeBackground': p(ss.surfaceContainerLow),
    'chat_outContactBackground': p(s.onPrimaryContainer),
    'chat_outContactIcon': p(s.onPrimaryContainer),
    'chat_outContactNameText': p(s.onPrimaryContainer),
    'chat_outContactPhoneSelectedText': p(s.onPrimaryContainer),
    'chat_outContactPhoneText': p(s.onPrimaryContainer),
    'chat_outFileBackground': p(s.onPrimaryContainer),
    'chat_outFileBackgroundSelected': p(s.onPrimaryContainer),
    'chat_outFileIcon': p(s.onPrimaryContainer),
    'chat_outFileInfoSelectedText': p(s.primary),
    'chat_outFileInfoText': p(s.primary),
    'chat_outFileNameText': p(s.onPrimaryContainer),
    'chat_outFileProgress': p(s.onPrimaryContainer),
    'chat_outFileProgressSelected': p(s.onPrimaryContainer),
    'chat_outFileSelectedIcon': p(ss.surfaceContainerLow),
    'chat_outForwardedNameText': p(s.outline),
    'chat_outGreenCall': -1,
    'chat_outInstant': p(s.onPrimaryContainer),
    'chat_outInstantSelected': p(s.onPrimaryContainer),
    'chat_outLinkSelectBackground': p(s.tertiaryContainer),
    'chat_outLoader': p(s.inverseSurface),
    'chat_outLoaderPhoto': p(s.primaryContainer),
    'chat_outLoaderPhotoIcon': p(s.inverseSurface),
    'chat_outLoaderPhotoIconSelected': p(s.inverseSurface),
    'chat_outLoaderPhotoSelected': p(s.primaryContainer),
    'chat_outLoaderSelected': p(s.inverseSurface),
    'chat_outLocationBackground': p(s.onPrimaryContainer),
    'chat_outLocationIcon': p(ss.surfaceContainerLow),
    'chat_outMediaIcon': p(s.onPrimaryContainer),
    'chat_outMediaIconSelected': p(s.onPrimaryContainer),
    'chat_outMenu': 0,
    'chat_outMenuSelected': 0,
    'chat_outPollCorrectAnswer': H['chat_outPollCorrectAnswer'],
    'chat_outPollWrongAnswer': p(s.error),
    'chat_outPreviewInstantSelectedText': p(s.onPrimaryContainer),
    'chat_outPreviewInstantText': p(s.onPrimaryContainer),
    'chat_outPreviewLine': p(s.outline),
    'chat_outPsaNameText': p(s.primary),
    'chat_outQuote': p(s.onSurfaceVariant),
    'chat_outReactionButtonBackground': p(s.primary),
    'chat_outReactionButtonText': p(s.onPrimaryContainer),
    'chat_outReactionButtonTextSelected': p(ss.surfaceContainerLow),
    'chat_outReplyLine': p(s.primary),
    'chat_outReplyLine2': p(s.error),
    'chat_outReplyMediaMessageSelectedText': p(s.primary),
    'chat_outReplyMediaMessageText': p(s.primary),
    'chat_outReplyMessageText': p(s.primary),
    'chat_outReplyNameText': p(s.primary),
    'chat_outSentCheck': p(s.outline),
    'chat_outSentCheckRead': p(s.outline),
    'chat_outSentCheckReadSelected': p(s.outline),
    'chat_outSentCheckSelected': p(s.outline),
    'chat_outSentClock': p(s.outline),
    'chat_outSentClockSelected': p(s.outline),
    'chat_outSiteNameText': p(s.outline),
    'chat_outTextSelectionCursor': p(s.primary),
    'chat_outTextSelectionHighlight': p(s.primaryContainer),
    'chat_outTimeSelectedText': p(s.outline),
    'chat_outTimeText': p(s.outline),
    'chat_outUpCall': p(s.onSurfaceVariant),
    'chat_outVenueInfoSelectedText': p(s.onPrimaryContainer),
    'chat_outVenueInfoText': p(s.onPrimaryContainer),
    'chat_outViaBotNameText': p(s.tertiary),
    'chat_outViews': p(s.outline),
    'chat_outViewsSelected': p(s.outline),
    'chat_outVoiceSeekbar': p(s.onSurfaceVariant),
    'chat_outVoiceSeekbarFill': p(s.onPrimaryContainer),
    'chat_outVoiceSeekbarSelected': p(s.onSurfaceVariant),
    'chat_previewDurationText': p(s.onSurface),
    'chat_previewGameText': p(s.onSurface),
    'chat_recordTime': p(s.onSurface),
    'chat_recordVoiceCancel': p(s.onSurface),
    'chat_recordedVoiceBackground': p(s.background),
    'chat_recordedVoiceDot': H['chat_recordedVoiceDot'],
    'chat_recordedVoicePlayPause': p(s.primary),
    'chat_recordedVoiceProgress': p(s.outlineVariant),
    'chat_recordedVoiceProgressInner': p(s.onSurfaceVariant),
    'chat_replyPanelClose': p(s.onSurface),
    'chat_replyPanelIcons': p(s.onSurface),
    'chat_replyPanelLine': p(ss.surfaceContainer),
    'chat_replyPanelMessage': p(s.onSurface),
    'chat_replyPanelName': p(s.onSurfaceVariant),
    'chat_reportSpam': H['chat_reportSpam'],
    'chat_searchPanelIcons': p(s.onSurface),
    'chat_searchPanelText': p(s.onSurface),
    'chat_secretChatStatusText': p(s.primary),
    'chat_secretTimeText': p(s.onSurface),
    'chat_secretTimerBackground': p(ss.surfaceContainerHigh),
    'chat_secretTimerText': p(s.onSurface),
    'chat_selectedBackground': p(s.primaryContainer),
    'chat_sentError': p(s.error),
    'chat_sentErrorIcon': p(s.error),
    'chat_serviceBackground': H['chat_serviceBackground'],
    'chat_serviceBackgroundSelected': H['chat_serviceBackgroundSelected'],
    'chat_serviceBackgroundSelector': p(ss.primaryFixed),
    'chat_serviceIcon': p(s.secondary),
    'chat_serviceLink': p(s.secondary),
    'chat_serviceText': p(s.secondary),
    'chat_status': p(s.primary),
    'chat_stickerNameText': p(ss.surfaceContainerHigh),
    'chat_stickerReplyLine': p(s.secondary),
    'chat_stickerReplyMessageText': p(s.secondary),
    'chat_stickerReplyNameText': p(s.secondary),
    'chat_stickerViaBotNameText': p(s.tertiary),
    'chat_stickersHintPanel': p(ss.surfaceContainerHigh),
    'chat_textSelectBackground': p(s.inversePrimary),
    'chat_topPanelBackground': p(ss.surfaceContainer),
    'chat_topPanelClose': p(s.onSurface),
    'chat_topPanelLine': p(s.onSurfaceVariant),
    'chat_topPanelMessage': p(s.onSurface),
    'chat_topPanelTitle': p(s.onSurfaceVariant),
    'chat_unreadMessagesStartArrowIcon': 0,
    'chat_unreadMessagesStartBackground': p(ss.surfaceContainerLow),
    'chat_unreadMessagesStartText': p(s.secondary),
    'chat_wallpaper': p(s.background),
    'chat_wallpaper_gradient_rotation': 0,
    'chat_wallpaper_gradient_to': 0,
    'chats_actionBackground': p(s.primaryContainer),
    'chats_actionIcon': p(s.onPrimaryContainer),
    'chats_actionMessage': p(s.onSurfaceVariant),
    'chats_actionPressedBackground': p(s.inversePrimary),
    'chats_actionUnreadBackground': p(s.primaryContainer),
    'chats_actionUnreadIcon': p(s.inverseSurface),
    'chats_actionUnreadPressedBackground': p(s.inversePrimary),
    'chats_archiveBackground': p(s.primary),
    'chats_archiveIcon': p(s.tertiaryContainer),
    'chats_archivePinBackground': p(s.secondary),
    'chats_archivePullDownBackground': H['chats_archivePullDownBackground'],
    'chats_archivePullDownBackgroundActive': H['chats_archivePullDownBackgroundActive'],
    'chats_archiveText': p(s.tertiaryContainer),
    'chats_attachMessage': p(s.onSurface),
    'chats_date': p(s.onSurfaceVariant),
    'chats_draft': p(s.error),
    'chats_mentionIcon': p(s.onPrimaryContainer),
    'chats_menuBackground': p(s.surface),
    'chats_menuCloud': p(s.onPrimary),
    'chats_menuCloudBackgroundCats': p(s.background),
    'chats_menuItemCheck': p(s.tertiaryContainer),
    'chats_menuItemIcon': p(s.onPrimary),
    'chats_menuItemText': p(s.onPrimary),
    'chats_menuName': p(s.onPrimary),
    'chats_menuPhone': p(s.onPrimary),
    'chats_menuPhoneCats': p(s.onPrimary),
    'chats_menuTopBackgroundCats': p(s.surface),
    'chats_menuTopShadow': 0,
    'chats_menuTopShadowCats': 0,
    'chats_message': p(s.onSurface),
    'chats_messageArchived': p(s.onSurface),
    'chats_message_threeLines': p(s.onSurface),
    'chats_muteIcon': p(s.onSurfaceVariant),
    'chats_name': p(s.onSurface),
    'chats_nameArchived': p(s.onSurface),
    'chats_nameIcon': p(ss.surfaceContainerHigh),
    'chats_nameMessage': p(s.secondary),
    'chats_nameMessageArchived': p(s.secondary),
    'chats_nameMessageArchived_threeLines': p(s.secondary),
    'chats_nameMessage_threeLines': p(s.secondary),
    'chats_onlineCircle': p(s.primary),
    'chats_pinnedIcon': p(s.onSurfaceVariant),
    'chats_pinnedOverlay': 0,
    'chats_secretIcon': H['chats_secretIcon'],
    'chats_secretName': H['chats_secretName'],
    'chats_sentCheck': p(s.onSurfaceVariant),
    'chats_sentClock': p(s.onSurfaceVariant),
    'chats_sentError': p(s.error),
    'chats_sentErrorIcon': p(s.error),
    'chats_sentReadCheck': p(s.onSurfaceVariant),
    'chats_tabUnreadActiveBackground': p(s.outline),
    'chats_tabUnreadUnactiveBackground': p(s.onSurface),
    'chats_tabletSelectedOverlay': p(ss.surfaceContainer),
    'chats_unreadCounter': p(s.secondaryContainer),
    'chats_unreadCounterMuted': p(s.inverseOnSurface),
    'chats_unreadCounterText': p(s.onSurface),
    'chats_verifiedBackground': p(s.primary),
    'chats_verifiedCheck': H['chats_verifiedCheck'],
    'checkbox': p(s.primary),
    'checkboxCheck': p(ss.surfaceContainerLow),
    'checkboxDisabled': p(s.primaryContainer),
    'checkboxSquareBackground': p(s.primary),
    'checkboxSquareCheck': p(ss.surfaceContainerHigh),
    'checkboxSquareDisabled': p(s.primary),
    'checkboxSquareUnchecked': p(s.outlineVariant),
    'code_background': H['code_background'],
    'code_comment': p(s.outlineVariant),
    'code_constannt': H['code_constannt'],
    'code_constant': H['code_constant'],
    'code_function': H['code_function'],
    'code_inBackground': H['code_inBackground'],
    'code_keyword': H['code_keyword'],
    'code_number': H['code_number'],
    'code_operator': H['code_operator'],
    'code_outBackground': p(s.secondaryContainer),
    'code_string': H['code_string'],
    'color_blue': H['color_blue'],
    'color_cyan': H['color_cyan'],
    'color_green': H['color_green'],
    'color_lightblue': H['color_lightblue'],
    'color_lightgreen': H['color_lightgreen'],
    'color_orange': H['color_orange'],
    'color_purple': H['color_purple'],
    'color_red': H['color_red'],
    'color_yellow': H['color_yellow'],
    'contacts_inviteBackground': p(s.onSurface),
    'contacts_inviteText': p(ss.surfaceContainerHigh),
    'contextProgressInner1': p(s.scrim),
    'contextProgressInner2': p(ss.surfaceContainer),
    'contextProgressInner3': p(s.onSurfaceVariant),
    'contextProgressInner4': p(s.scrim),
    'contextProgressOuter1': p(s.background),
    'contextProgressOuter2': p(s.outline),
    'contextProgressOuter3': p(s.inversePrimary),
    'contextProgressOuter4': p(s.background),
    'dialogBackground': p(s.background),
    'dialogBackgroundGray': p(ss.surfaceContainerLow),
    'dialogBadgeBackground': p(s.primaryContainer),
    'dialogBadgeText': p(s.inverseSurface),
    'dialogButton': p(s.primary),
    'dialogButtonSelector': p(s.primary),
    'dialogCameraIcon': p(s.primary),
    'dialogCardShadow': p(s.onSurface),
    'dialogCheckboxSquareBackground': p(s.primary),
    'dialogCheckboxSquareCheck': p(s.background),
    'dialogCheckboxSquareDisabled': p(ss.primaryFixed),
    'dialogCheckboxSquareUnchecked': p(s.primary),
    'dialogEmptyImage': p(s.onPrimaryContainer),
    'dialogEmptyText': p(s.onPrimaryContainer),
    'dialogFloatingButton': p(s.primaryContainer),
    'dialogFloatingButtonPressed': p(s.secondary),
    'dialogFloatingIcon': p(s.inverseSurface),
    'dialogGrayLine': p(s.background),
    'dialogIcon': p(s.primary),
    'dialogInputField': p(s.background),
    'dialogInputFieldActivated': p(s.primary),
    'dialogLineProgress': p(s.primary),
    'dialogLineProgressBackground': p(s.inversePrimary),
    'dialogLinkSelection': p(s.primary),
    'dialogProgressCircle': p(s.primary),
    'dialogRadioBackground': p(s.primary),
    'dialogRadioBackgroundChecked': p(s.primary),
    'dialogReactionMentionBackground': p(s.secondaryContainer),
    'dialogRedIcon': p(s.error),
    'dialogRoundCheckBox': p(s.primary),
    'dialogRoundCheckBoxCheck': p(s.background),
    'dialogScrollGlow': p(ss.surfaceContainer),
    'dialogSearchBackground': p(ss.surfaceContainerHigh),
    'dialogSearchHint': p(s.onSurfaceVariant),
    'dialogSearchIcon': p(s.onSurface),
    'dialogSearchText': p(s.onSurface),
    'dialogShadowLine': 0,
    'dialogSwipeRemove': p(s.tertiary),
    'dialogTextBlack': p(s.onSurface),
    'dialogTextBlue': p(s.onSurface),
    'dialogTextBlue2': p(s.onSurface),
    'dialogTextBlue3': p(s.onSurface),
    'dialogTextBlue4': p(s.onSurface),
    'dialogTextGray': p(s.onSurfaceVariant),
    'dialogTextGray2': p(s.onSurfaceVariant),
    'dialogTextGray3': p(s.onSurfaceVariant),
    'dialogTextGray4': p(s.onSurfaceVariant),
    'dialogTextHint': p(s.outlineVariant),
    'dialogTextLink': p(s.tertiary),
    'dialogTextRed': p(s.error),
    'dialogTextRed2': p(s.error),
    'dialogTopBackground': p(s.secondary),
    'dialog_inlineProgress': p(s.primary),
    'dialog_inlineProgressBackground': p(ss.surfaceContainerHigh),
    'dialog_liveLocationProgress': p(s.primary),
    'divider': 0,
    'emptyListPlaceholder': p(s.onSurface),
    'fastScrollActive': p(s.inversePrimary),
    'fastScrollInactive': p(s.primary),
    'fastScrollText': p(s.onSurface),
    'featuredStickers_addButton': p(s.primary),
    'featuredStickers_addButtonPressed': p(s.primary),
    'featuredStickers_addedIcon': p(s.primary),
    'featuredStickers_buttonProgress': p(s.primary),
    'featuredStickers_buttonText': p(ss.surfaceContainerHigh),
    'featuredStickers_removeButtonText': p(s.error),
    'featuredStickers_unread': p(s.primary),
    'files_folderIcon': p(s.background),
    'files_folderIconBackground': p(s.outlineVariant),
    'files_iconText': -1,
    'fill_RedNormal': p(s.error),
    'gift_ribbon': p(s.error),
    'gift_ribbon_soldout': p(s.onSurfaceVariant),
    'glass_defaultIcon': p(s.onSurfaceVariant),
    'glass_defaultText': p(s.onSurfaceVariant),
    'glass_targetMainTabs': p(s.background),
    'glass_targetMainTopPanel': p(s.surface),
    'graySection': p(ss.surfaceContainerHigh),
    'graySectionText': p(s.onSurfaceVariant),
    'groupcreate_cursor': p(s.primary),
    'groupcreate_hintText': p(ss.primaryFixed),
    'groupcreate_sectionShadow': H['groupcreate_sectionShadow'],
    'groupcreate_sectionText': p(ss.surfaceContainerHigh),
    'groupcreate_spanBackground': p(s.primaryContainer),
    'groupcreate_spanDelete': p(ss.primaryFixed),
    'groupcreate_spanText': H['groupcreate_spanText'],
    'inappPlayerBackground': p(ss.surfaceContainer),
    'inappPlayerClose': p(s.onSurface),
    'inappPlayerPerformer': p(s.onSurface),
    'inappPlayerPlayPause': p(s.onSurface),
    'inappPlayerTitle': p(s.onSurface),
    'iv_background': p(s.background),
    'iv_backgroundGray': p(s.surface),
    'iv_navigationBackground': p(ss.surfaceContainer),
    'key_chat_messagePanelVoiceLock': p(s.onPrimaryContainer),
    'key_chat_messagePanelVoiceLockBackground': p(s.secondaryContainer),
    'key_chat_messagePanelVoiceLockShadow': p(s.onSurface),
    'key_chat_recordedVoiceHighlight': H['key_chat_recordedVoiceHighlight'],
    'key_chat_wallpaper_gradient_to2': 0,
    'key_chat_wallpaper_gradient_to3': 0,
    'key_graySectionText': p(s.primary),
    'key_player_progressCachedBackground': p(s.inversePrimary),
    'key_sheet_other': p(s.outlineVariant),
    'key_sheet_scrollUp': p(s.outlineVariant),
    'kvoipgroup_overlayAlertMutedByAdmin2': p(s.tertiaryContainer),
    'listSelectorSDK21': p(s.inverseOnSurface),
    'location_actionActiveIcon': p(s.primary),
    'location_actionBackground': p(ss.surfaceContainerHigh),
    'location_actionIcon': p(s.primary),
    'location_actionPressedBackground': p(ss.surfaceContainerHigh),
    'location_liveLocationProgress': p(s.primary),
    'location_placeLocationBackground': p(ss.surfaceContainerHigh),
    'location_sendLiveLocationBackground': p(s.primary),
    'location_sendLiveLocationIcon': H['location_sendLiveLocationIcon'],
    'location_sendLiveLocationText': p(s.primary),
    'location_sendLocationBackground': p(s.primary),
    'location_sendLocationIcon': -1,
    'location_sendLocationText': p(s.primary),
    'login_progressInner': p(s.secondaryContainer),
    'login_progressOuter': p(ss.primaryFixed),
    'musicPicker_buttonBackground': p(s.primary),
    'musicPicker_buttonIcon': p(ss.surfaceContainerLow),
    'musicPicker_checkbox': p(s.primary),
    'musicPicker_checkboxCheck': p(s.onSurface),
    'passport_authorizeBackground': p(s.background),
    'passport_authorizeBackgroundSelected': p(s.background),
    'passport_authorizeText': p(s.onSurface),
    'picker_badge': H['picker_badge'],
    'picker_badgeText': p(s.onSurface),
    'picker_disabledButton': p(s.primary),
    'picker_enabledButton': p(s.primary),
    'player_actionBar': p(s.background),
    'player_actionBarItems': p(s.onSurface),
    'player_actionBarSelector': p(s.onSurface),
    'player_actionBarSubtitle': p(s.onSurfaceVariant),
    'player_actionBarTitle': p(s.onSurface),
    'player_actionBarTop': p(s.onSurface),
    'player_background': p(s.background),
    'player_button': p(s.onSurface),
    'player_buttonActive': p(s.onSurface),
    'player_progress': p(s.primary),
    'player_progressBackground': p(ss.surfaceContainerHigh),
    'player_progressBackground2': p(ss.surfaceContainerHigh),
    'player_progressCachedBackground': p(s.outlineVariant),
    'player_time': p(s.onSurfaceVariant),
    'premiumGradient0': H['premiumGradient0'],
    'premiumGradient1': H['premiumGradient1'],
    'premiumGradient2': H['premiumGradient2'],
    'premiumGradient3': H['premiumGradient3'],
    'premiumGradient4': H['premiumGradient4'],
    'premiumGradientBackground1': H['premiumGradientBackground1'],
    'premiumGradientBackground2': H['premiumGradientBackground2'],
    'premiumGradientBackground3': H['premiumGradientBackground3'],
    'premiumGradientBackground4': H['premiumGradientBackground4'],
    'premiumGradientBackgroundOverlay': H['premiumGradientBackgroundOverlay'],
    'premiumGradientBottomSheet1': H['premiumGradientBottomSheet1'],
    'premiumGradientBottomSheet2': H['premiumGradientBottomSheet2'],
    'premiumGradientBottomSheet3': H['premiumGradientBottomSheet3'],
    'premiumStarGradient1': H['premiumStarGradient1'],
    'premiumStarGradient2': H['premiumStarGradient2'],
    'premiumStartGradient1': H['premiumStartGradient1'],
    'premiumStartGradient2': H['premiumStartGradient2'],
    'premiumStartSmallStarsColor': H['premiumStartSmallStarsColor'],
    'premiumStartSmallStarsColor2': H['premiumStartSmallStarsColor2'],
    'profile_actionBackground': p(s.primaryContainer),
    'profile_actionIcon': p(s.inverseSurface),
    'profile_actionPressedBackground': p(s.inversePrimary),
    'profile_creatorIcon': p(s.primary),
    'profile_status': p(s.onSurface),
    'profile_tabSelectedLine': p(ss.primaryFixed),
    'profile_tabSelectedText': p(ss.primaryFixed),
    'profile_tabSelector': p(s.primary),
    'profile_tabText': p(s.outlineVariant),
    'profile_title': p(s.onSurface),
    'profile_verifiedBackground': p(s.primary),
    'profile_verifiedCheck': H['profile_verifiedCheck'],
    'progressCircle': p(s.primary),
    'radioBackground': p(s.primary),
    'radioBackgroundChecked': p(s.primary),
    'returnToCallBackground': p(ss.surfaceContainerHigh),
    'returnToCallMutedBackground': p(s.onSurfaceVariant),
    'returnToCallText': p(s.onSurface),
    'sessions_devicesImage': p(s.secondaryContainer),
    'share_icon': p(s.onErrorContainer),
    'share_linkBackground': p(s.error),
    'share_linkText': p(s.onErrorContainer),
    'sharedMedia_actionMode': p(s.tertiary),
    'sharedMedia_linkPlaceholder': p(s.primary),
    'sharedMedia_linkPlaceholderText': p(ss.surfaceContainerHigh),
    'sharedMedia_photoPlaceholder': p(s.primary),
    'sharedMedia_startStopLoadIcon': p(s.primary),
    'sheet_other': p(s.onSurface),
    'sheet_scrollUp': p(s.onSurface),
    'statisticChartActiveLine': p(ss.surfaceContainerHigh),
    'statisticChartActivePickerChart': p(s.primary),
    'statisticChartBackZoomColor': p(s.primary),
    'statisticChartCheckboxInactive': p(ss.surfaceContainerHigh),
    'statisticChartChevronColor': p(s.primary),
    'statisticChartHighlightColor': p(s.primary),
    'statisticChartHintLine': p(s.primary),
    'statisticChartInactivePickerChart': 0,
    'statisticChartLineEmpty': H['statisticChartLineEmpty'],
    'statisticChartLine_blue': H['statisticChartLine_blue'],
    'statisticChartLine_cyan': H['statisticChartLine_cyan'],
    'statisticChartLine_golden': H['statisticChartLine_golden'],
    'statisticChartLine_green': H['statisticChartLine_green'],
    'statisticChartLine_indigo': H['statisticChartLine_indigo'],
    'statisticChartLine_lightblue': p(s.outline),
    'statisticChartLine_lightgreen': H['statisticChartLine_lightgreen'],
    'statisticChartLine_orange': H['statisticChartLine_orange'],
    'statisticChartLine_purple': H['statisticChartLine_purple'],
    'statisticChartLine_red': H['statisticChartLine_red'],
    'statisticChartPopupBackground': p(s.background),
    'statisticChartRipple': p(s.onSurfaceVariant),
    'statisticChartSignature': p(s.primary),
    'statisticChartSignatureAlpha': p(s.primary),
    'stickers_menu': p(s.onSurface),
    'stickers_menuSelector': p(s.background),
    'stories_circle1': p(s.primary),
    'stories_circle2': p(s.primary),
    'stories_circle_closeFriends1': H['stories_circle_closeFriends1'],
    'stories_circle_closeFriends2': H['stories_circle_closeFriends2'],
    'stories_circle_dialog1': p(s.primary),
    'stories_circle_dialog2': p(s.primary),
    'switch2Track': p(s.outlineVariant),
    'switch2TrackChecked': p(ss.primaryFixed),
    'switchTrack': p(s.outlineVariant),
    'switchTrackBlue': p(s.outline),
    'switchTrackBlueChecked': p(s.outline),
    'switchTrackBlueSelector': p(s.outline),
    'switchTrackBlueSelectorChecked': p(s.outline),
    'switchTrackBlueThumb': p(ss.surfaceContainerHigh),
    'switchTrackBlueThumbChecked': p(ss.surfaceContainerHigh),
    'switchTrackChecked': p(ss.primaryFixed),
    'table_background': p(ss.surfaceContainer),
    'table_border': p(s.outlineVariant),
    'text_RedBold': p(s.error),
    'text_RedRegular': p(s.error),
    'topics_unreadCounter': p(s.primary),
    'topics_unreadCounterMuted': p(s.outlineVariant),
    'undo_background': p(s.primary),
    'undo_cancelColor': p(s.inversePrimary),
    'undo_infoColor': p(ss.surfaceContainerHigh),
    'voipgroup_actionBar': p(s.onSurface),
    'voipgroup_actionBarItems': -1,
    'voipgroup_actionBarItemsSelector': p(s.onSurfaceVariant),
    'voipgroup_actionBarSubtitle': -1,
    'voipgroup_actionBarUnscrolled': p(s.onSurface),
    'voipgroup_blueText': p(s.tertiaryContainer),
    'voipgroup_checkMenu': p(s.inversePrimary),
    'voipgroup_connectingProgress': p(s.primaryContainer),
    'voipgroup_dialogBackground': p(s.onSurface),
    'voipgroup_disabledButton': p(s.onSurface),
    'voipgroup_disabledButtonActive': p(s.onSurface),
    'voipgroup_disabledButtonActiveScrolled': p(s.onSurface),
    'voipgroup_emptyView': p(s.onSurface),
    'voipgroup_inviteMembersBackground': p(s.onSurface),
    'voipgroup_lastSeenText': p(s.outlineVariant),
    'voipgroup_lastSeenTextUnscrolled': p(s.outlineVariant),
    'voipgroup_leaveButton': H['voipgroup_leaveButton'],
    'voipgroup_leaveButtonScrolled': p(s.tertiaryContainer),
    'voipgroup_leaveCallMenu': p(s.secondaryContainer),
    'voipgroup_listSelector': p(s.onSurfaceVariant),
    'voipgroup_listViewBackground': p(s.onSurface),
    'voipgroup_listViewBackgroundUnscrolled': p(s.onSurface),
    'voipgroup_listeningText': H['voipgroup_listeningText'],
    'voipgroup_muteButton': p(s.outline),
    'voipgroup_muteButton2': H['voipgroup_muteButton2'],
    'voipgroup_muteButton3': p(s.onSurfaceVariant),
    'voipgroup_mutedByAdminGradient': p(s.tertiaryContainer),
    'voipgroup_mutedByAdminGradient2': p(s.tertiaryContainer),
    'voipgroup_mutedByAdminGradient3': H['voipgroup_mutedByAdminGradient3'],
    'voipgroup_mutedByAdminIcon': H['voipgroup_mutedByAdminIcon'],
    'voipgroup_mutedByAdminMuteButton': H['voipgroup_mutedByAdminMuteButton'],
    'voipgroup_mutedByAdminMuteButtonDisabled': p(s.tertiaryContainer),
    'voipgroup_mutedIcon': H['voipgroup_mutedIcon'],
    'voipgroup_mutedIconUnscrolled': H['voipgroup_mutedIconUnscrolled'],
    'voipgroup_nameText': -1,
    'voipgroup_overlayAlertGradientMuted': H['voipgroup_overlayAlertGradientMuted'],
    'voipgroup_overlayAlertGradientMuted2': p(s.primaryContainer),
    'voipgroup_overlayAlertGradientUnmuted': p(s.outline),
    'voipgroup_overlayAlertGradientUnmuted2': p(s.inversePrimary),
    'voipgroup_overlayAlertMutedByAdmin': H['voipgroup_overlayAlertMutedByAdmin'],
    'voipgroup_overlayAlertMutedByAdmin2': p(s.errorContainer),
    'voipgroup_overlayBlue1': H['voipgroup_overlayBlue1'],
    'voipgroup_overlayBlue2': p(s.primaryContainer),
    'voipgroup_overlayGreen1': p(s.outline),
    'voipgroup_overlayGreen2': p(s.inversePrimary),
    'voipgroup_scrollUp': p(s.outline),
    'voipgroup_searchBackground': p(s.onSurfaceVariant),
    'voipgroup_searchPlaceholder': p(s.outlineVariant),
    'voipgroup_searchText': -1,
    'voipgroup_soundButton': H['voipgroup_soundButton'],
    'voipgroup_soundButton2': p(s.outline),
    'voipgroup_soundButtonActive': H['voipgroup_soundButtonActive'],
    'voipgroup_soundButtonActive2': p(s.outline),
    'voipgroup_soundButtonActive2Scrolled': p(s.outline),
    'voipgroup_soundButtonActiveScrolled': H['voipgroup_soundButtonActiveScrolled'],
    'voipgroup_speakingText': p(s.secondaryContainer),
    'voipgroup_topPanelBlue1': p(ss.surfaceContainerHigh),
    'voipgroup_topPanelBlue2': p(s.outlineVariant),
    'voipgroup_topPanelGray': p(ss.surfaceContainerHigh),
    'voipgroup_topPanelGreen1': p(s.onSurfaceVariant),
    'voipgroup_topPanelGreen2': p(s.outline),
    'voipgroup_unmuteButton': p(s.secondary),
    'voipgroup_unmuteButton2': H['voipgroup_unmuteButton2'],
    'voipgroup_windowBackgroundWhiteInputField': -1,
    'voipgroup_windowBackgroundWhiteInputFieldActivated': -1,
    'wallet_blackBackground': p(s.scrim),
    'wallet_greenText': H['wallet_greenText'],
    'wallpaperFileOffset': 0,
    'windowBackgroundCheckText': p(s.primary),
    'windowBackgroundChecked': p(s.background),
    'windowBackgroundGray': p(s.background),
    'windowBackgroundGrayShadow': 0,
    'windowBackgroundUnchecked': p(s.background),
    'windowBackgroundWhite': p(s.surface),
    'windowBackgroundWhiteBlackText': p(s.onSurface),
    'windowBackgroundWhiteBlueButton': p(s.primary),
    'windowBackgroundWhiteBlueHeader': p(s.primary),
    'windowBackgroundWhiteBlueIcon': p(s.onSurface),
    'windowBackgroundWhiteBlueText': p(s.onSurface),
    'windowBackgroundWhiteBlueText2': p(s.onSurface),
    'windowBackgroundWhiteBlueText3': p(s.onSurface),
    'windowBackgroundWhiteBlueText4': p(s.onSurface),
    'windowBackgroundWhiteBlueText5': p(s.onSurface),
    'windowBackgroundWhiteBlueText6': p(s.onSurface),
    'windowBackgroundWhiteBlueText7': p(s.onSurface),
    'windowBackgroundWhiteGrayIcon': p(s.onSurfaceVariant),
    'windowBackgroundWhiteGrayLine': p(s.onSurfaceVariant),
    'windowBackgroundWhiteGrayText': p(s.onSurfaceVariant),
    'windowBackgroundWhiteGrayText2': p(s.onSurfaceVariant),
    'windowBackgroundWhiteGrayText3': p(s.onSurfaceVariant),
    'windowBackgroundWhiteGrayText4': p(s.onSurfaceVariant),
    'windowBackgroundWhiteGrayText5': p(s.onSurfaceVariant),
    'windowBackgroundWhiteGrayText6': p(s.onSurfaceVariant),
    'windowBackgroundWhiteGrayText7': p(s.onSurfaceVariant),
    'windowBackgroundWhiteGrayText8': p(s.onSurfaceVariant),
    'windowBackgroundWhiteGreenText': H['windowBackgroundWhiteGreenText'],
    'windowBackgroundWhiteGreenText2': H['windowBackgroundWhiteGreenText2'],
    'windowBackgroundWhiteHintText': p(s.onSurfaceVariant),
    'windowBackgroundWhiteInputField': p(s.onSurfaceVariant),
    'windowBackgroundWhiteInputFieldActivated': p(s.primary),
    'windowBackgroundWhiteLinkSelection': p(s.outlineVariant),
    'windowBackgroundWhiteLinkText': p(s.tertiary),
    'windowBackgroundWhiteRedText': p(s.error),
    'windowBackgroundWhiteRedText2': p(s.error),
    'windowBackgroundWhiteRedText3': p(s.error),
    'windowBackgroundWhiteRedText4': p(s.error),
    'windowBackgroundWhiteRedText5': p(s.error),
    'windowBackgroundWhiteRedText6': p(s.error),
    'windowBackgroundWhiteValueText': p(s.primary),
    'windowBackgroundWhiteYellowText': p(s.primary),
  };
  return Object.entries(tokens)
    .map(([key, val]) => `${key}=${val}`)
    .join('\n');
}
export function downloadAttheme(content, filename = 'TeleYou.attheme') {
  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}