import { hexFromArgb } from '@material/material-color-utilities';
function toHex(argb) {
  return hexFromArgb(argb);
}
export function generateDesktopColors(scheme) {
  const s = scheme;
  const surface          = toHex(s.surface);
  const onSurface        = toHex(s.onSurface);
  const onPrimary        = toHex(s.onPrimary);
  const primary          = toHex(s.primary);
  const primaryContainer = toHex(s.primaryContainer);
  const primaryFixed     = toHex(s.primaryFixed     ?? s.primaryContainer);
  const secondaryContainer = toHex(s.secondaryContainer);
  const secondary        = toHex(s.secondary);
  const tertiary         = toHex(s.tertiary);
  const onSurfaceVariant = toHex(s.onSurfaceVariant);
  const outline          = toHex(s.outline);
  const outlineVariant   = toHex(s.outlineVariant);
  const surfaceContainerHigh     = toHex(s.surfaceContainerHigh     ?? s.surfaceVariant);
  const surfaceContainerHighest  = toHex(s.surfaceContainerHighest  ?? s.surfaceVariant);
  const surfaceContainerLow      = toHex(s.surfaceContainerLow      ?? s.surfaceVariant);
  const scrim            = toHex(s.scrim ?? s.shadow ?? 0xFF000000);
  const error            = toHex(s.error);
  const errorContainer   = toHex(s.errorContainer);
  const inversePrimary   = toHex(s.inversePrimary);
  const TOKEN = {
    surface, onSurface, onPrimary, primary, primaryContainer, primaryFixed,
    secondaryContainer, secondary, tertiary, onSurfaceVariant,
    outline, outlineVariant, surfaceContainerHigh, surfaceContainerHighest,
    surfaceContainerLow, scrim, error, errorContainer, inversePrimary,
  };
  const lines = [];
  lines.push(`windowBg: ${surface}; // white: fallback for background`);
  lines.push(`windowFg: ${onSurface}; // black: fallback for text`);
  lines.push(`windowBgOver: ${surfaceContainerHigh}; // light gray: fallback for background with mouse over`);
  lines.push(`windowBgRipple: ${surfaceContainerHighest}; // darker gray: fallback for ripple effect`);
  lines.push(`windowFgOver: ${onSurface}; // black: fallback for text with mouse over`);
  lines.push(`windowSubTextFg: ${onSurfaceVariant}; // gray: fallback for additional text`);
  lines.push(`windowSubTextFgOver: ${onSurfaceVariant}; // darker gray: fallback for additional text with mouse over`);
  lines.push(`windowBoldFg: ${onSurface}; // dark gray: fallback for bold text`);
  lines.push(`windowBoldFgOver: ${onSurface}; // dark gray: fallback for bold text with mouse over`);
  lines.push(`windowBgActive: ${primary}; // bright blue: fallback for blue filled active areas`);
  lines.push(`windowFgActive: ${onPrimary}; // white: fallback for text on active areas`);
  lines.push(`windowActiveTextFg: ${primary}; // online blue: fallback for active text like online status`);
  lines.push(`windowShadowFg: ${scrim}; // black: fallback for shadow`);
  lines.push(`windowShadowFgFallback: ${surfaceContainerHigh}; // gray: fallback for shadow without opacity`);
  lines.push("shadowFg: #00000018; // most shadows (including opacity)");
  lines.push("slideFadeOutBg: #0000003c; // slide animation (chat to profile) fade out filling");
  lines.push(`slideFadeOutShadowFg: ${scrim}; // slide animation (chat to profile) fade out right section shadow`);
  lines.push(`imageBg: ${scrim}; // image background fallback (when photo size is less than minimum allowed)`);
  lines.push("imageBgTransparent: #ffffff; // image background when displaying an image with opacity where no opacity is needed");
  lines.push(`activeButtonBg: ${primary}; // default active button background`);
  lines.push(`activeButtonBgOver: ${primary}; // default active button background with mouse over`);
  lines.push(`activeButtonBgRipple: ${primaryFixed}; // default active button ripple effect`);
  lines.push(`activeButtonFg: ${onPrimary}; // default active button text`);
  lines.push(`activeButtonFgOver: ${onPrimary}; // default active button text with mouse over`);
  lines.push(`activeButtonSecondaryFg: ${primaryContainer}; // default active button additional text (selected messages counter in forward / delete buttons)`);
  lines.push(`activeButtonSecondaryFgOver: ${primaryContainer}; // default active button additional text with mouse over`);
  lines.push(`activeLineFg: ${primary}; // default active line (like code input field bottom border when you log in and field is focused)`);
  lines.push(`activeLineFgError: ${error}; // default active line for error state (like code input field bottom border when you log in and you've entered incorrect code)`);
  lines.push(`lightButtonBg: ${surface}; // default light button background (like buttons in boxes)`);
  lines.push(`lightButtonBgOver: ${primaryContainer}; // default light button background with mouse over`);
  lines.push(`lightButtonBgRipple: ${primaryFixed}; // default light button ripple effect`);
  lines.push(`lightButtonFg: ${primary}; // default light button text`);
  lines.push(`lightButtonFgOver: ${primary}; // default light button text with mouse over`);
  lines.push(`attentionButtonFg: ${error}; // default attention button text (like confirm button on log out)`);
  lines.push(`attentionButtonFgOver: ${error}; // default attention button text with mouse over`);
  lines.push(`attentionButtonBgOver: ${errorContainer}; // default attention button background with mouse over`);
  lines.push(`attentionButtonBgRipple: ${errorContainer}; // default attention button ripple effect`);
  lines.push(`menuBg: ${surface}; // default popup menu background`);
  lines.push(`menuBgOver: ${surfaceContainerHigh}; // default popup menu item background with mouse over`);
  lines.push(`menuBgRipple: ${surfaceContainerHighest}; // default popup menu item ripple effect`);
  lines.push(`menuIconFg: ${onSurfaceVariant}; // default popup menu item icon (like main menu)`);
  lines.push(`menuIconFgOver: ${onSurfaceVariant}; // default popup menu item icon with mouse over`);
  lines.push("menuSubmenuArrowFg: #373737; // default popup menu submenu arrow icon (like in message field context menu in case of RTL system language)");
  lines.push(`menuFgDisabled: ${outline}; // default popup menu item disabled text (like unavailable items in message field context menu)`);
  lines.push(`menuSeparatorFg: ${surfaceContainerHigh}; // default popup menu separator (like in message field context menu)`);
  lines.push("scrollBarBg: #00000053; // default scroll bar current rectangle, the bar itself (like in chats list)");
  lines.push("scrollBarBgOver: #0000007a; // default scroll bar current rectangle with mouse over it");
  lines.push("scrollBg: #0000001a; // default scroll bar background");
  lines.push("scrollBgOver: #0000002c; // default scroll bar background with mouse over the scroll bar");
  lines.push(`smallCloseIconFg: ${outlineVariant}; // small X icon (like in Show all sessions box to the right for sessions termination)`);
  lines.push("smallCloseIconFgOver: #a3a3a3; // small X icon with mouse over");
  lines.push(`radialFg: ${onPrimary}; // default radial loader line (like in Media Viewer when loading a photo)`);
  lines.push("radialBg: #00000056; // default radial loader background (like in Media Viewer when loading a photo)");
  lines.push(`placeholderFg: ${onSurfaceVariant}; // default input field placeholder when field is not focused (like in phone input field when you log in)`);
  lines.push("placeholderFgActive: #aaaaaa; // default input field placeholder when field is focused");
  lines.push("inputBorderFg: #e0e0e0; // default input field bottom border (like in code input field when you log in and field is not focused)");
  lines.push("filterInputBorderFg: #54c3f3; // default rounded input field border (like in chats list search field when field is focused)");
  lines.push(`filterInputActiveBg: ${surface}; // default rounded input field active background (like in chats list search field when field is focused)`);
  lines.push(`filterInputInactiveBg: ${surfaceContainerHigh}; // default rounded input field inactive background (like in chats list search field when field is inactive)`);
  lines.push("checkboxFg: #b3b3b3; // default unchecked checkbox rounded rectangle");
  lines.push(`botKbBg: ${surfaceContainerHigh}; // bot keyboard button background`);
  lines.push(`botKbDownBg: ${surfaceContainerHighest}; // bot keyboard button ripple effect`);
  lines.push(`botKbColor: ${onSurface}; // bot keyboard button text`);
  lines.push("botKbPrimaryBg: #298acfcc; // bot keyboard Primary button background");
  lines.push("botKbDangerBg: #e05356cc; // bot keyboard Danger button background");
  lines.push("botKbSuccessBg: #61c752cc; // bot keyboard Success button background");
  lines.push("botKbInlinePrimaryBg: #378eaeb3; // inline bot keyboard Primary button background");
  lines.push("botKbInlineDangerBg: #c9543eb3; // inline bot keyboard Danger button background");
  lines.push("botKbInlineSuccessBg: #489d38b3; // inline bot keyboard Success button background");
  lines.push(`sliderBgInactive: ${surfaceContainerLow}; // default slider not active bar (like in Settings when you choose interface scale or custom notifications count)`);
  lines.push(`sliderBgActive: ${primary}; // default slider active bar (like in Settings when you choose interface scale or custom notifications count)`);
  lines.push("tooltipBg: #eef2f5; // tooltip background (like when you put mouse over the message timestamp and wait)");
  lines.push("tooltipFg: #5d6c80; // tooltip text");
  lines.push("tooltipBorderFg: #c9d1db; // tooltip border");
  lines.push("titleShadow: #00000003; // one pixel line shadow at the bottom of custom window title");
  lines.push(`titleBg: ${surfaceContainerHigh}; // custom window title background when window is inactive`);
  lines.push(`titleBgActive: ${surfaceContainerHigh}; // custom window title background when window is active`);
  lines.push(`titleButtonBg: ${surfaceContainerHigh}; // custom window title minimize/maximize/restore button background when window is inactive (Windows only)`);
  lines.push(`titleButtonFg: ${outline}; // custom window title minimize/maximize/restore button icon when window is inactive (Windows only)`);
  lines.push(`titleButtonBgOver: ${surfaceContainerHighest}; // custom window title minimize/maximize/restore button background with mouse over when window is inactive (Windows only)`);
  lines.push(`titleButtonFgOver: ${onSurfaceVariant}; // custom window title minimize/maximize/restore button icon with mouse over when window is inactive (Windows only)`);
  lines.push(`titleButtonBgActive: ${surfaceContainerHigh}; // custom window title minimize/maximize/restore button background when window is active (Windows only)`);
  lines.push(`titleButtonFgActive: ${outline}; // custom window title minimize/maximize/restore button icon when window is active (Windows only)`);
  lines.push(`titleButtonBgActiveOver: ${surfaceContainerHighest}; // custom window title minimize/maximize/restore button background with mouse over when window is active (Windows only)`);
  lines.push(`titleButtonFgActiveOver: ${onSurfaceVariant}; // custom window title minimize/maximize/restore button icon with mouse over when window is active (Windows only)`);
  lines.push(`titleButtonCloseBg: ${surfaceContainerHigh}; // custom window title close button background when window is inactive (Windows only)`);
  lines.push(`titleButtonCloseFg: ${outline}; // custom window title close button icon when window is inactive (Windows only)`);
  lines.push("titleButtonCloseBgOver: #e81123; // custom window title close button background with mouse over when window is inactive (Windows only)");
  lines.push(`titleButtonCloseFgOver: ${onPrimary}; // custom window title close button icon with mouse over when window is inactive (Windows only)`);
  lines.push(`titleButtonCloseBgActive: ${surfaceContainerHigh}; // custom window title close button background when window is active (Windows only)`);
  lines.push(`titleButtonCloseFgActive: ${outline}; // custom window title close button icon when window is active (Windows only)`);
  lines.push("titleButtonCloseBgActiveOver: titleButtonCloseBgOver; // custom window title close button background with mouse over when window is active (Windows only)");
  lines.push(`titleButtonCloseFgActiveOver: ${onPrimary}; // custom window title close button icon with mouse over when window is active (Windows only)`);
  lines.push("titleFg: #acacac; // custom window title text when window is inactive (Windows 11 and macOS)");
  lines.push("titleFgActive: #3e3c3e; // custom window title text when window is active (Windows 11 and macOS)");
  lines.push(`trayCounterBg: ${primary}; // tray icon counter background`);
  lines.push("trayCounterBgMute: #888888; // tray icon counter background if all unread messages are muted");
  lines.push(`trayCounterFg: ${onPrimary}; // tray icon counter text`);
  lines.push("trayCounterBgMacInvert: #ffffff; // tray icon counter background when tray icon is pressed or when dark theme of macOS is used (macOS only)");
  lines.push("trayCounterFgMacInvert: #ffffff01; // tray icon counter text when tray icon is pressed or when dark theme of macOS is used (macOS only)");
  lines.push("layerBg: #0000007f; // box and main menu background layer fade");
  lines.push(`cancelIconFg: ${onSurfaceVariant}; // default for settings close icon and box search cancel icon`);
  lines.push(`cancelIconFgOver: ${onSurfaceVariant}; // default for settings close icon and box search cancel icon with mouse over`);
  lines.push(`boxBg: ${surface}; // box background`);
  lines.push(`boxTextFg: ${onSurface}; // box text`);
  lines.push(`boxTextFgGood: ${tertiary}; // accepted box text (like when choosing username that is not occupied)`);
  lines.push(`boxTextFgError: ${error}; // rejecting box text (like when choosing username that is occupied)`);
  lines.push("boxTitleFg: #404040; // box title text");
  lines.push("boxSearchBg: boxBg; // box search field background (like in contacts box)");
  lines.push("boxTitleAdditionalFg: #808080; // box title additional text (like in create group box when you see chosen members count)");
  lines.push(`boxTitleCloseFg: ${onSurfaceVariant}; // settings close icon and box search cancel icon (like in contacts box)`);
  lines.push(`boxTitleCloseFgOver: ${onSurfaceVariant}; // settings close icon and box search cancel icon (like in contacts box) with mouse over`);
  lines.push(`boxDividerBg: ${surfaceContainerHigh}; // gray divider in boxes and layers`);
  lines.push(`boxDividerFg: ${scrim}; // gray divider shadow in boxes and layers`);
  lines.push("paymentsTipActive: #01ad0f; // tip button text in payments checkout form");
  lines.push(`membersAboutLimitFg: ${onSurfaceVariant}; // text in channel members box about the limit (max 200 last members are shown)`);
  lines.push(`contactsBg: ${surface}; // contacts (and some other) box row background`);
  lines.push(`contactsBgOver: ${surfaceContainerHigh}; // contacts (and some other) box row background with mouse over`);
  lines.push(`contactsNameFg: ${onSurface}; // contacts (and some other) box row name text`);
  lines.push(`contactsStatusFg: ${onSurfaceVariant}; // contacts (and some other) box row additional text (like last seen stamp)`);
  lines.push(`contactsStatusFgOver: ${onSurfaceVariant}; // contacts (and some other) box row additional text (like last seen stamp) with mouse over`);
  lines.push(`contactsStatusFgOnline: ${primary}; // contacts (and some other) box row active additional text (like online status)`);
  lines.push("photoCropFadeBg: layerBg; // avatar crop box fade background (when choosing a new photo in Settings or for a group)");
  lines.push("photoCropPointFg: #ffffff7f; // avatar crop box corner rectangles (when choosing a new photo in Settings or for a group)");
  lines.push("callArrowFg: #2dad2d; // received phone call arrow (in calls list box)");
  lines.push("callArrowMissedFg: #dd5b4a; // missed phone call arrow (in calls list box)");
  lines.push(`introBg: ${surface}; // login background`);
  lines.push(`introTitleFg: ${onSurface}; // login title text`);
  lines.push(`introDescriptionFg: ${onSurfaceVariant}; // login description text`);
  lines.push("introCoverTopBg: #0f89d0; // intro gradient top (from)");
  lines.push("introCoverBottomBg: #39b0f0; // intro gradient bottom (to)");
  lines.push("introCoverIconsFg: #5ec6ff; // intro cloud graphics");
  lines.push("introCoverPlaneTrace: #5ec6ff69; // intro plane traces");
  lines.push("introCoverPlaneInner: #c6d8e8; // intro plane part");
  lines.push("introCoverPlaneOuter: #a1bed4; // intro plane part");
  lines.push(`introCoverPlaneTop: ${onPrimary}; // intro plane part`);
  lines.push(`dialogsMenuIconFg: ${onSurfaceVariant}; // main menu and passcode lock icon`);
  lines.push(`dialogsMenuIconFgOver: ${onSurfaceVariant}; // main menu and passcode lock icon with mouse over`);
  lines.push(`dialogsBg: ${surface}; // chat list background`);
  lines.push(`dialogsNameFg: ${onSurface}; // chat list name text`);
  lines.push(`dialogsChatIconFg: ${onSurface}; // chat list group or channel icon`);
  lines.push(`dialogsDateFg: ${onSurfaceVariant}; // chat list date text`);
  lines.push(`dialogsTextFg: ${onSurfaceVariant}; // chat list message text`);
  lines.push(`dialogsTextFgService: ${primary}; // chat list group sender name text (or media message type text)`);
  lines.push("dialogsDraftFg: #dd4b39; // chat list draft label");
  lines.push(`dialogsVerifiedIconBg: ${primary}; // chat list verified icon background`);
  lines.push(`dialogsVerifiedIconFg: ${onPrimary}; // chat list verified icon check`);
  lines.push("dialogsSendingIconFg: #c1c1c1; // chat list sending message icon (clock)");
  lines.push(`dialogsSentIconFg: ${tertiary}; // chat list sent message tick / double tick icon`);
  lines.push(`dialogsUnreadBg: ${primary}; // chat list unread badge background for not muted chat`);
  lines.push(`dialogsUnreadBgMuted: ${outline}; // chat list unread badge background for muted chat`);
  lines.push(`dialogsUnreadFg: ${onPrimary}; // chat list unread badge text`);
  lines.push(`dialogsArchiveFg: ${onSurfaceVariant}; // chat list archive name text`);
  lines.push(`dialogsOnlineBadgeFg: ${tertiary}; // chat list online status`);
  lines.push("dialogsScamFg: dialogsDraftFg; // chat list scam label");
  lines.push(`dialogsBgOver: ${surfaceContainerHigh}; // chat list background with mouse over`);
  lines.push(`dialogsNameFgOver: ${onSurface}; // chat list name text with mouse over`);
  lines.push(`dialogsChatIconFgOver: ${onSurface}; // chat list group or channel icon with mouse over`);
  lines.push(`dialogsDateFgOver: ${onSurfaceVariant}; // chat list date text with mouse over`);
  lines.push(`dialogsTextFgOver: ${onSurfaceVariant}; // chat list message text with mouse over`);
  lines.push(`dialogsTextFgServiceOver: ${primary}; // chat list group sender name text with mouse over`);
  lines.push("dialogsDraftFgOver: dialogsDraftFg; // chat list draft label with mouse over");
  lines.push(`dialogsVerifiedIconBgOver: ${primary}; // chat list verified icon background with mouse over`);
  lines.push("dialogsVerifiedIconFgOver: dialogsVerifiedIconFg; // chat list verified icon check with mouse over");
  lines.push("dialogsSendingIconFgOver: dialogsSendingIconFg; // chat list sending message icon (clock) with mouse over");
  lines.push(`dialogsSentIconFgOver: ${tertiary}; // chat list sent message tick / double tick icon with mouse over`);
  lines.push(`dialogsUnreadBgOver: ${primary}; // chat list unread badge background for not muted chat with mouse over`);
  lines.push(`dialogsUnreadBgMutedOver: ${outline}; // chat list unread badge background for muted chat with mouse over`);
  lines.push("dialogsUnreadFgOver: dialogsUnreadFg; // chat list unread badge text with mouse over");
  lines.push(`dialogsArchiveFgOver: ${onSurfaceVariant}; // chat list archive name text with mouse over`);
  lines.push("dialogsScamFgOver: dialogsDraftFgOver; // chat list scam label with mouse over");
  lines.push(`dialogsBgActive: ${surfaceContainerHighest}; // chat list background for current (active) chat`);
  lines.push(`dialogsNameFgActive: ${onSurface}; // chat list name text for current (active) chat`);
  lines.push("dialogsChatIconFgActive: dialogsNameFgActive; // chat list group or channel icon for current (active) chat");
  lines.push(`dialogsDateFgActive: ${onSurfaceVariant}; // chat list date text for current (active) chat`);
  lines.push(`dialogsTextFgActive: ${onSurfaceVariant}; // chat list message text for current (active) chat`);
  lines.push("dialogsTextFgServiceActive: dialogsTextFgActive; // chat list group sender name text for current (active) chat");
  lines.push(`dialogsDraftFgActive: ${error}; // chat list draft label for current (active) chat`);
  lines.push("dialogsVerifiedIconBgActive: dialogsTextFgActive; // chat list verified icon background for current (active) chat");
  lines.push(`dialogsVerifiedIconFgActive: ${onSurface}; // chat list verified icon check for current (active) chat`);
  lines.push("dialogsSendingIconFgActive: #ffffff99; // chat list sending message icon (clock) for current (active) chat");
  lines.push(`dialogsSentIconFgActive: ${tertiary}; // chat list sent message tick / double tick icon for current (active) chat`);
  lines.push(`dialogsUnreadBgActive: ${primary}; // chat list unread badge background for not muted chat for current (active) chat`);
  lines.push(`dialogsUnreadBgMutedActive: ${outline}; // chat list unread badge background for muted chat for current (active) chat`);
  lines.push(`dialogsUnreadFgActive: ${onPrimary}; // chat list unread badge text for current (active) chat`);
  lines.push(`dialogsOnlineBadgeFgActive: ${tertiary}; // chat list online status for current (active) chat`);
  lines.push(`dialogsScamFgActive: ${error}; // chat list scam label for current (active) chat`);
  lines.push(`dialogsRippleBg: ${surfaceContainerHighest}; // chat list background ripple effect`);
  lines.push(`dialogsRippleBgActive: ${surfaceContainerHighest}; // chat list background ripple effect for current (active) chat`);
  lines.push(`searchedBarBg: ${surfaceContainerHigh}; // search results bar background (in chats list, contacts box..)`);
  lines.push(`searchedBarFg: ${onSurfaceVariant}; // search results bar text (in chats list, contacts box..)`);
  lines.push(`topBarBg: ${surface}; // top bar background (in chat view, media overview..)`);
  lines.push(`emojiPanBg: ${surface}; // emoji panel background`);
  lines.push("emojiPanCategories: #f7f7f7; // emoji panel categories background");
  lines.push(`emojiPanHeaderFg: ${onSurfaceVariant}; // emoji panel section header text`);
  lines.push("emojiPanHeaderBg: #fffffff2; // emoji panel section header background");
  lines.push(`emojiIconFg: ${onSurfaceVariant}; // emoji category icon`);
  lines.push("emojiSubIconFgActive: #666666; // active emoji subcategory icon");
  lines.push(`stickerPanDeleteBg: ${scrim}; // delete X button background for custom sent stickers in stickers panel (legacy)`);
  lines.push(`stickerPanDeleteFg: ${onPrimary}; // delete X button icon for custom sent stickers in stickers panel (legacy)`);
  lines.push("stickerPreviewBg: #ffffffb0; // sticker and GIF preview background (when you press and hold on a sticker)");
  lines.push("stickerPanPremium1: #5a99ff; // premium sticker pack icon gradient 1");
  lines.push("stickerPanPremium2: #45b9f3; // premium sticker pack icon gradient 2");
  lines.push(`historyTextInFg: ${onSurface}; // inbox message text`);
  lines.push(`historyTextInFgSelected: ${onSurface}; // inbox message selected text or text in a selected message`);
  lines.push(`historyTextOutFg: ${onSurface}; // outbox message text`);
  lines.push(`historyTextOutFgSelected: ${onSurface}; // outbox message selected text or text in a selected message`);
  lines.push(`historyLinkInFg: ${primary}; // inbox message link`);
  lines.push(`historyLinkInFgSelected: ${primary}; // inbox message link in a selected text or message`);
  lines.push(`historyLinkOutFg: ${primary}; // outbox message link`);
  lines.push(`historyLinkOutFgSelected: ${primary}; // outbox message link in a selected text or message`);
  lines.push(`historyFileNameInFg: ${onSurface}; // inbox media filename text`);
  lines.push(`historyFileNameInFgSelected: ${onSurface}; // inbox media filename text in a selected message`);
  lines.push(`historyFileNameOutFg: ${onSurface}; // outbox media filename text`);
  lines.push(`historyFileNameOutFgSelected: ${onSurface}; // outbox media filename text in a selected message`);
  lines.push("historyOutIconFg: #57b84c; // outbox message tick / double tick icon");
  lines.push("historyOutIconFgSelected: #45a3aa; // outbox message tick / double tick icon in a selected message");
  lines.push(`historyIconFgInverted: ${onPrimary}; // media message tick / double tick icon (like in sent photo)`);
  lines.push("historySendingOutIconFg: #98d292; // outbox sending message icon (clock)");
  lines.push("historySendingInIconFg: #a0adb5; // inbox sending message icon (clock) (like in sent messages to yourself or in sent messages to a channel)");
  lines.push("historySendingInvertedIconFg: #ffffffc8; // media sending message icon (clock) (like in sent photo)");
  lines.push("historyCallArrowInFg: #32b032; // received phone call arrow");
  lines.push("historyCallArrowInFgSelected: #2592a8; // received phone call arrow in a selected message");
  lines.push("historyCallArrowMissedInFg: callArrowMissedFg; // missed phone call arrow");
  lines.push("historyCallArrowMissedInFgSelected: callArrowMissedFg; // missed phone call arrow in a selected message");
  lines.push("historyCallArrowOutFg: historyCallArrowInFg; // outgoing phone call arrow");
  lines.push("historyCallArrowOutFgSelected: historyCallArrowInFgSelected; // outgoing phone call arrow");
  lines.push("historyUnreadBarBg: #fcfbfa; // new unread messages bar background");
  lines.push("historyUnreadBarBorder: shadowFg; // new unread messages bar shadow");
  lines.push(`historyUnreadBarFg: ${secondary}; // new unread messages bar text`);
    lines.push('historyForwardChooseBg: #0000004c; // forwarding messages in a large window size "choose recipient" background');
  lines.push(`historyForwardChooseFg: ${onPrimary}; // forwarding messages in a large window size "choose recipient" text`);
  lines.push("historyPeer1NameFg: #c03d33; // red group member name");
  lines.push("historyPeer1NameFgSelected: historyPeer1NameFg; // red group member name in a selected message");
  lines.push("historyPeer1UserpicBg: #ff845e; // red userpic background");
  lines.push("historyPeer2NameFg: #4fad2d; // green group member name");
  lines.push("historyPeer2NameFgSelected: historyPeer2NameFg; // green group member name in a selected message");
  lines.push("historyPeer2UserpicBg: #9ad164; // green userpic background");
  lines.push("historyPeer3NameFg: #d09306; // yellow group member name (actually unused)");
  lines.push("historyPeer3NameFgSelected: historyPeer3NameFg; // yellow group member name in a selected message (actually unused)");
  lines.push("historyPeer3UserpicBg: #e5ca77; // yellow userpic background (actually unused)");
  lines.push(`historyPeer4NameFg: ${primary}; // blue group member name`);
  lines.push(`historyPeer4NameFgSelected: ${primary}; // blue group member name in a selected message`);
  lines.push("historyPeer4UserpicBg: #5caffa; // blue userpic background");
  lines.push("historyPeer5NameFg: #8544d6; // purple group member name");
  lines.push("historyPeer5NameFgSelected: historyPeer5NameFg; // purple group member name in a selected message");
  lines.push("historyPeer5UserpicBg: #b694f9; // purple userpic background");
  lines.push("historyPeer6NameFg: #cd4073; // pink group member name");
  lines.push("historyPeer6NameFgSelected: historyPeer6NameFg; // pink group member name in a selected message");
  lines.push("historyPeer6UserpicBg: #ff8aac; // pink userpic background");
  lines.push("historyPeer7NameFg: #2996ad; // sea group member name");
  lines.push("historyPeer7NameFgSelected: historyPeer7NameFg; // sea group member name in a selected message");
  lines.push("historyPeer7UserpicBg: #5bcbe3; // sea userpic background");
  lines.push("historyPeer8NameFg: #ce671b; // orange group member name");
  lines.push("historyPeer8NameFgSelected: historyPeer8NameFg; // orange group member name in a selected message");
  lines.push("historyPeer8UserpicBg: #febb5b; // orange userpic background");
  lines.push(`historyPeerUserpicFg: ${onPrimary}; // default userpic initials`);
  lines.push("historyPeerSavedMessagesBg: historyPeer4UserpicBg; // saved messages userpic background");
  lines.push(`historyPeerArchiveUserpicBg: ${outline}; // archive folder userpic background`);
  lines.push("historyPeer1UserpicBg2: #d45246; // the second red userpic background");
  lines.push("historyPeer2UserpicBg2: #46ba43; // the second green userpic background");
  lines.push("historyPeer3UserpicBg2: #e5ca77; // the second yellow userpic background (actually unused)");
  lines.push("historyPeer4UserpicBg2: #408acf; // the second blue userpic background");
  lines.push("historyPeer5UserpicBg2: #6c61df; // the second purple userpic background");
  lines.push("historyPeer6UserpicBg2: #d95574; // the second pink userpic background");
  lines.push("historyPeer7UserpicBg2: #359ad4; // the second sea userpic background");
  lines.push("historyPeer8UserpicBg2: #f68136; // the second orange userpic background");
  lines.push("historyPeerSavedMessagesBg2: historyPeer4UserpicBg2; // the second saved messages userpic background");
  lines.push("settingsIconBg1: #f06964; // red settings icon background");
  lines.push("settingsIconBg2: #6dc534; // green settings icon background");
  lines.push("settingsIconBg3: #ed9f20; // light-orange settings icon background");
  lines.push("settingsIconBg4: #56b3f5; // light-blue settings icon background");
  lines.push("settingsIconBg5: #7595ff; // dark-blue settings icon background");
  lines.push("settingsIconBg6: #b580e2; // purple settings icon background");
  lines.push("settingsIconBg8: #f2925b; // dark-orange settings icon background");
  lines.push("settingsIconBgArchive: #9da2b0; // archive main menu icon background");
  lines.push(`settingsIconFg: ${onPrimary}; // settings icon shape`);
  lines.push("historyScrollBarBg: #517c417a; // scroll bar current rectangle, the bar itself in the chat view (adjusted)");
  lines.push("historyScrollBarBgOver: #517c41bc; // scroll bar current rectangle with mouse over it in the chat view (adjusted)");
  lines.push("historyScrollBg: #517c414c; // scroll bar background (adjusted)");
  lines.push("historyScrollBgOver: #517c416b; // scroll bar background with mouse over the scroll bar (adjusted)");
  lines.push(`msgInBg: ${surface}; // inbox message background`);
  lines.push(`msgInBgSelected: ${primaryContainer}; // inbox selected message background (and background of selected text in those messages)`);
  lines.push(`msgOutBg: ${primaryContainer}; // outbox message background`);
  lines.push(`msgOutBgSelected: ${secondaryContainer}; // outbox selected message background (and background of selected text in those messages)`);
  lines.push("msgSelectOverlay: #358cd44c; // overlay which is filling the media parts of selected messages (like in selected photo message)");
  lines.push("msgStickerOverlay: #358cd47f; // overlay which is filling the selected sticker message");
  lines.push(`msgInServiceFg: ${primary}; // inbox message information text (like information about a forwarded message original sender)`);
  lines.push(`msgInServiceFgSelected: ${primary}; // inbox selected message information text (like information about a forwarded message original sender)`);
  lines.push("msgOutServiceFg: #45a32d; // outbox message information text (like information about a forwarded message original sender)");
  lines.push("msgOutServiceFgSelected: #469992; // outbox message information text (like information about a forwarded message original sender)");
  lines.push("msgInShadow: #748ea229; // inbox message shadow (below the bubble)");
  lines.push("msgInShadowSelected: #548dbb29; // inbox selected message shadow (below the bubble)");
  lines.push("msgOutShadow: #3ac3461d; // outbox message shadow (below the bubble)");
  lines.push("msgOutShadowSelected: #37a78d22; // outbox selected message shadow (below the bubble)");
  lines.push(`msgInDateFg: ${outlineVariant}; // inbox message time text`);
  lines.push(`msgInDateFgSelected: ${secondary}; // inbox selected message time text`);
  lines.push("msgOutDateFg: #6db566; // outbox message time text");
  lines.push("msgOutDateFgSelected: #56b2a6; // outbox selected message time text");
  lines.push(`msgServiceFg: ${onPrimary}; // service message text (like date dividers or service message about the group title being changed)`);
  lines.push("msgServiceBg: #517c417f; // service message background (like in a service message about group title being changed) (adjusted)");
  lines.push("msgServiceBgSelected: #96b38ba2; // service message selected text background (like in a service message about group title being changed) (adjusted)");
  lines.push(`msgInReplyBarColor: ${primary}; // inbox message reply outline`);
  lines.push(`msgInReplyBarSelColor: ${primary}; // inbox selected message reply outline`);
  lines.push("msgOutReplyBarColor: #5eb854; // outbox message reply outline");
  lines.push("msgOutReplyBarSelColor: historyOutIconFgSelected; // outbox selected message reply outline");
  lines.push("msgImgReplyBarColor: msgServiceFg; // sticker message reply outline");
  lines.push("msgInMonoFg: #4e7391; // inbox message monospace text (like a message sent with `test` text)");
  lines.push("msgOutMonoFg: #459866; // outbox message monospace text");
  lines.push("msgInMonoFgSelected: msgInMonoFg; // inbox message monospace text in a selected text or message");
  lines.push("msgOutMonoFgSelected: msgOutMonoFg; // outbox message monospace text in a selected text or message");
  lines.push(`msgDateImgFg: ${onPrimary}; // media message time text (like time text in a sent photo)`);
  lines.push("msgDateImgBg: #00000054; // media message time bubble background (like time bubble in a sent photo) or file with thumbnail download icon circle background");
  lines.push("msgDateImgBgOver: #00000074; // media message download icon circle background with mouse over (like file with thumbnail download icon)");
  lines.push("msgDateImgBgSelected: #1c4a7187; // selected media message time bubble background");
  lines.push(`msgFileThumbLinkInFg: ${primary}; // inbox media file message with thumbnail download / open with button text`);
  lines.push(`msgFileThumbLinkInFgSelected: ${primary}; // inbox selected media file message with thumbnail download / open with button text`);
  lines.push("msgFileThumbLinkOutFg: #4ba831; // outbox media file message with thumbnail download / open with button text");
  lines.push("msgFileThumbLinkOutFgSelected: #31a298; // outbox selected media file message with thumbnail download / open with button text");
  lines.push(`msgFileInBg: ${primary}; // inbox audio file download circle background`);
  lines.push("msgFileInBgOver: #4eade3; // inbox audio file download circle background with mouse over");
  lines.push(`msgFileInBgSelected: ${primaryFixed}; // inbox selected audio file download circle background`);
  lines.push("msgFileOutBg: #5fbe67; // outbox audio file download circle background");
  lines.push("msgFileOutBgSelected: #50ac9b; // outbox selected audio file download circle background");
  lines.push("msgFile1Bg: #72b1df; // blue shared links / files without image square thumbnail");
  lines.push("msgFile1BgDark: #5c9ece; // blue shared files without image download circle background");
  lines.push("msgFile1BgOver: #5294c4; // blue shared files without image download circle background with mouse over");
  lines.push("msgFile1BgSelected: #5099d0; // blue shared files without image download circle background if file is selected");
  lines.push("msgFile2Bg: #5fbe67; // green shared links / shared files without image square thumbnail");
  lines.push("msgFile2BgDark: #4da859; // green shared files without image download circle background");
  lines.push("msgFile2BgOver: #44a050; // green shared files without image download circle background with mouse over");
  lines.push("msgFile2BgSelected: #50ac9b; // green shared files without image download circle background if file is selected");
  lines.push("msgFile3Bg: #e47272; // red shared links / shared files without image square thumbnail");
  lines.push("msgFile3BgDark: #cd5b5e; // red shared files without image download circle background");
  lines.push("msgFile3BgOver: #c35154; // red shared files without image download circle background with mouse over");
  lines.push("msgFile3BgSelected: #9f6a82; // red shared files without image download circle background if file is selected");
  lines.push("msgFile4Bg: #efc274; // yellow shared links / shared files without image square thumbnail");
  lines.push("msgFile4BgDark: #e6a561; // yellow shared files without image download circle background");
  lines.push("msgFile4BgOver: #dc9c5a; // yellow shared files without image download circle background with mouse over");
  lines.push("msgFile4BgSelected: #b19d84; // yellow shared files without image download circle background if file is selected");
  lines.push(`historyFileInIconFg: ${onPrimary}; // inbox file without thumbnail (like audio file) download arrow icon`);
  lines.push(`historyFileInIconFgSelected: ${primaryContainer}; // inbox selected file without thumbnail (like audio file) download arrow icon`);
  lines.push(`historyFileInRadialFg: ${onPrimary}; // inbox file without thumbnail (like audio file) radial download animation line`);
  lines.push(`historyFileInRadialFgSelected: ${primaryContainer}; // inbox selected file without thumbnail (like audio file) radial download animation line`);
  lines.push(`historyFileOutIconFg: ${primaryContainer}; // outbox file without thumbnail (like audio file) download arrow icon`);
  lines.push(`historyFileOutIconFgSelected: ${secondaryContainer}; // outbox selected file without thumbnail (like audio file) download arrow icon`);
  lines.push(`historyFileOutRadialFg: ${primaryContainer}; // outbox file without thumbnail (like audio file) radial download animation line`);
  lines.push(`historyFileOutRadialFgSelected: ${secondaryContainer}; // outbox selected file without thumbnail (like audio file) radial download animation line`);
  lines.push(`historyFileThumbIconFg: ${onPrimary}; // file with thumbnail (or photo / video) download arrow icon`);
  lines.push(`historyFileThumbIconFgSelected: ${primaryContainer}; // selected file with thumbnail (or photo / video) download arrow icon`);
  lines.push(`historyFileThumbRadialFg: ${onPrimary}; // file with thumbnail (or photo / video) radial download animation line`);
  lines.push(`historyFileThumbRadialFgSelected: ${primaryContainer}; // selected file with thumbnail (or photo / video) radial download animation line`);
  lines.push(`historyVideoMessageProgressFg: ${onPrimary}; // radial playback progress in round video messages`);
  lines.push(`msgWaveformInActive: ${primary}; // inbox voice message active waveform lines (like played part of currently playing voice message)`);
  lines.push(`msgWaveformInActiveSelected: ${primaryFixed}; // inbox selected voice message active waveform lines (like played part of currently playing voice message)`);
  lines.push("msgWaveformInInactive: #d4dee6; // inbox voice message inactive waveform lines (like upcoming part of currently playing voice message)");
  lines.push("msgWaveformInInactiveSelected: #9cc1e1; // inbox selected voice message inactive waveform lines (like upcoming part of currently playing voice message)");
  lines.push("msgWaveformOutActive: #5ebd66; // outbox voice message active waveform lines (like played part of currently playing voice message)");
  lines.push("msgWaveformOutActiveSelected: #6badad; // outbox selected voice message active waveform lines (like played part of currently playing voice message)");
  lines.push("msgWaveformOutInactive: #b3e2b4; // outbox voice message inactive waveform lines (like upcoming part of currently playing voice message)");
  lines.push("msgWaveformOutInactiveSelected: #91c3c3; // outbox selected voice message inactive waveform lines (like upcoming part of currently playing voice message)");
  lines.push("msgBotKbOverBgAdd: #ffffff20; // this is painted over a bot inline keyboard button (which has msgServiceBg background) when mouse is over that button");
  lines.push("msgBotKbIconFg: msgServiceFg; // bot inline keyboard button icon in the top-right corner (like in @vote bot when a poll is ready to be shared)");
  lines.push("msgBotKbRippleBg: #00000020; // bot inline keyboard button ripple effect");
  lines.push(`mediaInFg: ${outlineVariant}; // inbox media message status text (like in file that is being downloaded)`);
  lines.push(`mediaInFgSelected: ${secondary}; // inbox selected media message status text (like in file that is being downloaded)`);
  lines.push("mediaOutFg: msgOutDateFg; // outbox media message status text (like in file that is being downloaded)");
  lines.push("mediaOutFgSelected: msgOutDateFgSelected; // outbox selected media message status text (like in file that is being downloaded)");
  lines.push("youtubePlayIconBg: #e83131c8; // youtube play icon background (when a link to a youtube video with a webpage preview is sent)");
  lines.push(`youtubePlayIconFg: ${onPrimary}; // youtube play icon arrow (when a link to a youtube video with a webpage preview is sent)`);
  lines.push("videoPlayIconBg: #0000007f; // other video play icon background (like when a link to a vimeo video with a webpage preview is sent)");
  lines.push(`videoPlayIconFg: ${onPrimary}; // other video play icon arrow (like when a link to a vimeo video with a webpage preview is sent)`);
  lines.push("toastBg: #2c3033e5; // toast notification background (like when you click on your t.me link when editing your username)");
  lines.push(`toastFg: ${onPrimary}; // toast notification text (like when you click on your t.me link when editing your username)`);
  lines.push(`historyToDownBg: ${surface}; // arrow button background (to scroll to the end of the viewed chat)`);
  lines.push(`historyToDownBgOver: ${surfaceContainerHigh}; // arrow button background with mouse over`);
  lines.push(`historyToDownBgRipple: ${surfaceContainerHighest}; // arrow button ripple effect`);
  lines.push(`historyToDownFg: ${onSurfaceVariant}; // arrow button icon`);
  lines.push(`historyToDownFgOver: ${onSurfaceVariant}; // arrow button icon with mouse over`);
  lines.push("historyToDownShadow: #00000040; // arrow button shadow");
  lines.push(`historyComposeAreaBg: ${surface}; // history compose area background (message write area / reply information / forwarding information)`);
  lines.push(`historyComposeAreaFg: ${onSurface}; // history compose area text`);
  lines.push(`historyComposeAreaFgService: ${outlineVariant}; // history compose area text when replying to a media message`);
  lines.push(`historyComposeIconFg: ${onSurfaceVariant}; // history compose area icon (like emoji, attach, bot command..)`);
  lines.push(`historyComposeIconFgOver: ${onSurfaceVariant}; // history compose area icon with mouse over`);
  lines.push(`historySendIconFg: ${primary}; // send message icon`);
  lines.push(`historySendIconFgOver: ${primary}; // send message icon with mouse over`);
  lines.push(`historyPinnedBg: ${surface}; // pinned message area background`);
  lines.push(`historyReplyBg: ${surface}; // reply / forward / edit message area background`);
  lines.push(`historyReplyIconFg: ${primary}; // reply / forward / edit message left icon`);
  lines.push(`historyReplyCancelFg: ${onSurfaceVariant}; // reply / forward / edit message cancel button`);
  lines.push(`historyReplyCancelFgOver: ${onSurfaceVariant}; // reply / forward / edit message cancel button with mouse over`);
  lines.push(`historyComposeButtonBg: ${surface}; // unblock / join channel / mute channel button background`);
  lines.push(`historyComposeButtonBgOver: ${surfaceContainerHigh}; // unblock / join channel / mute channel button background with mouse over`);
  lines.push(`historyComposeButtonBgRipple: ${surfaceContainerHighest}; // unblock / join channel / mute channel button ripple effect`);
  lines.push("mapPointDrop: #fd4444; // geo location marker background");
  lines.push(`mapPointDot: ${onPrimary}; // geo location marker point`);
  lines.push("overviewCheckBg: #00000040; // shared media / files / links checkbox background for not selected rows when some rows are selected");
  lines.push(`overviewCheckBgActive: ${primary}; // shared media / files / links checkbox background for selected rows`);
  lines.push(`overviewCheckBorder: ${onPrimary}; // shared media round checkbox border`);
  lines.push(`overviewCheckFgActive: ${onPrimary}; // shared files / links checkbox icon for selected rows`);
  lines.push("overviewPhotoSelectOverlay: #40ace333; // shared photos / videos / links fill for selected rows");
  lines.push("profileStatusFgOver: #7c99b2; // group members list in group profile user last seen text with mouse over");
  lines.push(`profileVerifiedCheckBg: ${primary}; // profile verified check icon background`);
  lines.push(`profileVerifiedCheckFg: ${onPrimary}; // profile verified check icon tick`);
  lines.push(`profileAdminStartFg: ${primary}; // group members list creator star icon`);
  lines.push(`notificationsBoxMonitorFg: ${onSurface}; // custom notifications settings box monitor color`);
  lines.push(`notificationsBoxScreenBg: ${primary}; // #6389a8; // custom notifications settings box monitor screen background`);
  lines.push(`notificationSampleUserpicFg: ${primary}; // custom notifications settings box small sample userpic placeholder`);
  lines.push("notificationSampleCloseFg: #d7d7d7; // custom notifications settings box small sample close button placeholder");
  lines.push("notificationSampleTextFg: #d7d7d7; // custom notifications settings box small sample text placeholder");
  lines.push("notificationSampleNameFg: #939393; // custom notifications settings box small sample name placeholder");
  lines.push(`mainMenuBg: ${surface}; // main menu background`);
  lines.push(`mainMenuCoverBg: ${primary}; // main menu top cover background`);
  lines.push("mainMenuCloudFg: activeButtonFg; // main menu top cover saved messages / archive button icon");
  lines.push("mainMenuCloudBg: #2785bf; // main menu top cover saved messages / archive button background");
  lines.push(`mediaPlayerBg: ${surface}; // audio file player background`);
  lines.push(`mediaPlayerActiveFg: ${primary}; // audio file player playback progress already played part`);
  lines.push(`mediaPlayerInactiveFg: ${surfaceContainerLow}; // audio file player playback progress upcoming (not played yet) part with mouse over`);
  lines.push("mediaPlayerDisabledFg: #9dd1ef; // audio file player loading progress (when you're playing an audio file and switch to the previous one which is not loaded yet)");
  lines.push(`mediaviewFileBg: ${surface}; // file rectangle background (when you view a png file in Media Viewer and go to a previous, not loaded yet, file)`);
  lines.push(`mediaviewFileNameFg: ${onSurface}; // file name in file rectangle`);
  lines.push(`mediaviewFileSizeFg: ${onSurfaceVariant}; // file size text in file rectangle`);
  lines.push("mediaviewFileRedCornerFg: #d55959; // red file thumbnail placeholder corner in file rectangle (for a file without thumbnail, like .pdf)");
  lines.push("mediaviewFileYellowCornerFg: #e8a659; // yellow file thumbnail placeholder corner in file rectangle (for a file without thumbnail, like .zip)");
  lines.push("mediaviewFileGreenCornerFg: #49a957; // green file thumbnail placeholder corner in file rectangle (for a file without thumbnail, like .exe)");
  lines.push("mediaviewFileBlueCornerFg: #599dcf; // blue file thumbnail placeholder corner in file rectangle (for a file without thumbnail, like .dmg)");
  lines.push("mediaviewFileExtFg: activeButtonFg; // file extension text in file thumbnail placeholder in file rectangle");
  lines.push("mediaviewMenuBg: #383838; // context menu in Media Viewer background");
  lines.push("mediaviewMenuBgOver: #505050; // context menu item background with mouse over");
  lines.push("mediaviewMenuBgRipple: #676767; // context menu item ripple effect");
  lines.push(`mediaviewMenuFg: ${onPrimary}; // context menu item text`);
  lines.push("mediaviewBg: #222222eb; // Media Viewer background");
  lines.push(`mediaviewVideoBg: ${scrim}; // Media Viewer background when viewing a video in full screen`);
  lines.push("mediaviewControlBg: #0000003c; // controls background (like next photo / previous photo)");
  lines.push(`mediaviewControlFg: ${onPrimary}; // controls icon (like next photo / previous photo)`);
  lines.push("mediaviewCaptionBg: #11111180; // caption text background (when viewing photo with caption)");
  lines.push(`mediaviewCaptionFg: ${onPrimary}; // caption text`);
  lines.push(`mediaviewTextLinkFg: ${secondary}; // caption text link`);
  lines.push("mediaviewSaveMsgBg: toastBg; // save to file toast message background in Media Viewer");
  lines.push("mediaviewSaveMsgFg: toastFg; // save to file toast message text");
  lines.push(`mediaviewPlaybackActive: ${outlineVariant}; // video playback progress already played part`);
  lines.push("mediaviewPlaybackInactive: #252525; // video playback progress upcoming (not played yet) part");
  lines.push("mediaviewPlaybackActiveOver: #ffffff; // video playback progress already played part with mouse over");
  lines.push("mediaviewPlaybackInactiveOver: #474747; // video playback progress upcoming (not played yet) part with mouse over");
  lines.push("mediaviewPlaybackProgressFg: #ffffffc7; // video playback progress text");
  lines.push(`mediaviewPlaybackIconFg: ${outlineVariant}; // video playback controls icon`);
  lines.push(`mediaviewPlaybackIconFgOver: ${onPrimary}; // video playback controls icon with mouse over`);
  lines.push("mediaviewPlaybackIconRipple: #ffffff14; // video playback controls ripple effect");
  lines.push("mediaviewPipControlsFg: #ffffffd9; // picture-in-picture controls");
  lines.push("mediaviewPipControlsFgOver: #ffffff; // picture-in-picture controls with mouse over");
  lines.push("mediaviewPipPlaybackActive: #ffffffda; // picture-in-picture playback progress already played part");
  lines.push("mediaviewPipPlaybackInactive: #ffffff26; // picture-in-picture playback progress upcoming (not played yet) part");
  lines.push(`mediaviewTransparentBg: ${surface}; // transparent filling part (when viewing a transparent .png file in Media Viewer)`);
  lines.push(`mediaviewTransparentFg: ${outline}; // another transparent filling part`);
  lines.push(`notificationBg: ${surface}; // custom notification window background`);
  lines.push("callBg: #26282cf2; // old phone call popup background");
  lines.push("callBgOpaque: #1b1f23; // phone call popup background");
  lines.push("callBgButton: #1b1f237f; // phone call window control buttons bg");
  lines.push(`callNameFg: ${onPrimary}; // phone call popup name text`);
  lines.push("callStatusFg: #aaabac; // phone call popup status text");
  lines.push("callIconBg: #ffffff1f; // phone call mute mic and camera button background");
  lines.push(`callIconFg: ${onPrimary}; // phone call popup answer, hangup, mute mic and camera icon`);
  lines.push("callIconBgActive: #ffffffe5; // phone call line busy cancel, muted mic and camera button background");
  lines.push(`callIconFgActive: ${onSurface}; // phone call line busy cancel, muted mic and camera icon`);
  lines.push(`callIconActiveRipple: ${surfaceContainerHigh}; // phone call line busy cancel, muted mic and camera ripple effect`);
  lines.push("callAnswerBg: #66c95b; // phone call popup answer button background");
  lines.push("callAnswerRipple: #52b149; // phone call popup answer button ripple effect");
  lines.push("callAnswerBgOuter: #50eb4126; // phone call popup answer button outer ripple effect");
  lines.push("callHangupBg: #d75a5a; // phone call popup hangup button background");
  lines.push("callHangupRipple: #c04646; // phone call popup hangup button ripple effect");
  lines.push("callMuteRipple: #ffffff12; // phone call popup mute mic and camera ripple effect");
  lines.push("groupCallBg: #1a2026; // group call popup background");
  lines.push(`groupCallActiveFg: ${secondary}; // group call active controls text`);
  lines.push("groupCallMembersBg: #2c333d; // group call members list background");
  lines.push("groupCallMembersBgOver: #323a45; // group call members list row with mouse over");
  lines.push("groupCallMembersBgRipple: #39424f; // group call member row ripple effect");
  lines.push(`groupCallMembersFg: ${onPrimary}; // group call member name text`);
  lines.push("groupCallMemberActiveIcon: #8deb90; // group call active member icon");
  lines.push("groupCallMemberActiveStatus: #8deb90; // group call active member status text");
  lines.push("groupCallMemberInactiveIcon: #84888f; // group call inactive member icon");
  lines.push("groupCallMemberInactiveStatus: #61c0ff; // group call inactive member status text");
  lines.push("groupCallMemberMutedIcon: #ed7372; // group call muted by admin member icon");
  lines.push("groupCallMemberNotJoinedStatus: #91979e; // group call non joined member status text");
  lines.push(`groupCallIconFg: ${onPrimary}; // group call mute / settings / leave icon`);
  lines.push("groupCallLive1: #0dcc39; // group call live button color1");
  lines.push("groupCallLive2: #0bb6bd; // group call live button color2");
  lines.push("groupCallMuted1: #0992ef; // group call muted button color1");
  lines.push("groupCallMuted2: #16ccfb; // group call muted button color2");
  lines.push("groupCallForceMutedBar1: #c65493; // group call force muted top bar color1");
  lines.push("groupCallForceMutedBar2: #7a6af1; // group call force muted top bar color2");
  lines.push("groupCallForceMutedBar3: #5f95e8; // group call force muted top bar color3");
  lines.push("groupCallForceMuted1: #4f9cff; // group call force muted button color1");
  lines.push("groupCallForceMuted2: #9b52e9; // group call force muted button color2");
  lines.push("groupCallForceMuted3: #eb5353; // group call force muted button color3");
  lines.push("groupCallMenuBg: #292d33; // group call popup menu background");
  lines.push("groupCallMenuBgOver: #343940; // group call popup menu with mouse over");
  lines.push("groupCallMenuBgRipple: #3a4047; // group call popup menu ripple effect");
  lines.push("groupCallLeaveBg: #f75c5c7f; // group call leave button background");
  lines.push("groupCallLeaveBgRipple: #f75c5c9e; // group call leave button ripple effect");
  lines.push("groupCallVideoTextFg: #ffffffe0; // group call text over video");
  lines.push("groupCallVideoSubTextFg: #ffffffc0; // group call additional text over video");
  lines.push(`callBarBg: ${primary}; // active phone call bar background`);
  lines.push(`callBarMuteRipple: ${primaryFixed}; // active phone call bar mute and hangup button ripple effect`);
  lines.push("callBarBgMuted: #8f8f8f; // phone call bar with muted mic background");
  lines.push(`callBarFg: ${onPrimary}; // phone call bar text and icons`);
  lines.push("importantTooltipBg: toastBg; // group call important tooltip background color");
  lines.push("importantTooltipFg: toastFg; // group call important tooltip text color");
  lines.push(`importantTooltipFgLink: ${secondary}; // group call important tooltip text link color`);
  lines.push(`outdatedFg: ${onPrimary}; // operating system version is outdated bar text`);
  lines.push("outdateSoonBg: #e08543; // operating system version is soon outdated bar background");
  lines.push("outdatedBg: #e05745; // operating system version is already outdated bar background");
  lines.push("spellUnderline: #ff000088; // misspelled words");
  lines.push("walletTitleBg: #121213; // wallet window title background when window is inactive");
  lines.push("walletTitleBgActive: walletTitleBg; // wallet window title background when window is active");
  lines.push("walletTitleButtonBg: walletTitleBg; // wallet window title minimize/maximize/restore button background when window is inactive (Windows only)");
  lines.push("walletTitleButtonFg: #5a5a5b; // wallet window title minimize/maximize/restore button icon when window is inactive (Windows only)");
  lines.push("walletTitleButtonBgOver: #373738; // wallet window title minimize/maximize/restore button background with mouse over when window is inactive (Windows only)");
  lines.push("walletTitleButtonFgOver: #747475; // wallet window title minimize/maximize/restore button icon with mouse over when window is inactive (Windows only)");
  lines.push("walletTitleButtonBgActive: walletTitleButtonBg; // wallet window title minimize/maximize/restore button background when window is active (Windows only)");
  lines.push("walletTitleButtonFgActive: walletTitleButtonFg; // wallet window title minimize/maximize/restore button icon when window is active (Windows only)");
  lines.push("walletTitleButtonBgActiveOver: walletTitleButtonBgOver; // wallet window title minimize/maximize/restore button background with mouse over when window is active (Windows only)");
  lines.push("walletTitleButtonFgActiveOver: walletTitleButtonFgOver; // wallet window title minimize/maximize/restore button icon with mouse over when window is active (Windows only)");
  lines.push("walletTitleButtonCloseBg: walletTitleButtonBg; // wallet window title close button background when window is inactive (Windows only)");
  lines.push("walletTitleButtonCloseFg: walletTitleButtonFg; // wallet window title close button icon when window is inactive (Windows only)");
  lines.push("walletTitleButtonCloseBgOver: titleButtonCloseBgOver; // wallet window title close button background with mouse over when window is inactive (Windows only)");
  lines.push("walletTitleButtonCloseFgOver: titleButtonCloseFgOver; // wallet window title close button icon with mouse over when window is inactive (Windows only)");
  lines.push("walletTitleButtonCloseBgActive: walletTitleButtonCloseBg; // wallet window title close button background when window is active (Windows only)");
  lines.push("walletTitleButtonCloseFgActive: walletTitleButtonCloseFg; // wallet window title close button icon when window is active (Windows only)");
  lines.push("walletTitleButtonCloseBgActiveOver: walletTitleButtonCloseBgOver; // wallet window title close button background with mouse over when window is active (Windows only)");
  lines.push("walletTitleButtonCloseFgActiveOver: walletTitleButtonCloseFgOver; // wallet window title close button icon with mouse over when window is active (Windows only)");
  lines.push("walletTopBg: #1e1f21; // wallet top part background");
  lines.push("walletBalanceFg: #ffffff; // wallet balance text");
  lines.push("walletSubBalanceFg: #f9f9f9; // wallet balance label text");
  lines.push(`walletTopLabelFg: ${onSurfaceVariant}; // wallet top updated label text`);
  lines.push(`walletTopIconFg: ${onSurfaceVariant}; // wallet top refresh and menu icons`);
  lines.push("walletTopIconRipple: #ffffff12; // wallet top menu icon ripple effect");
  lines.push("sideBarBg: #293a4c; // filters side bar background");
  lines.push("sideBarBgActive: #17212b; // filters side bar active background");
  lines.push("sideBarBgRipple: #1e2b38; // filters side bar ripple effect");
  lines.push("sideBarTextFg: #8897a6; // filters side bar text");
  lines.push("sideBarTextFgActive: #64b9fa; // filters side bar active item text");
  lines.push("sideBarIconFg: #8393a3; // filters side bar icon");
  lines.push("sideBarIconFgActive: #5eb5f7; // filters side bar active item icon");
  lines.push("sideBarBadgeBg: #5eb5f7; // filters side bar badge background");
  lines.push("sideBarBadgeBgMuted: #8393a3; // filters side bar unimportant badge background");
  lines.push(`sideBarBadgeFg: ${onPrimary}; // filters side bar badge text`);
  lines.push("songCoverOverlayFg: #00000066; // song cover overlay");
  lines.push("photoEditorItemBaseHandleFg: #3ccaef; // photo editor handle circle");
  lines.push("premiumButtonBg1: #55a5ff; // upgrade to premium button gradient 1");
  lines.push("premiumButtonBg2: #a767ff; // upgrade to premium button gradient 2");
  lines.push("premiumButtonBg3: #db5c9d; // upgrade to premium button gradient 3");
  lines.push("premiumButtonFg: #ffffff; // upgrade to premium button text");
  lines.push("premiumIconBg1: #f38926; // icon in premium settings gradient 1");
  lines.push("premiumIconBg2: #e44456; // icon in premium settings gradient 2");
  lines.push("premiumIconBg3: #4acd43; // icon in premium settings gradient 3");
  lines.push("statisticsChartInactive: #e2eef999; // inactive area in footer of statistic charts");
  lines.push("statisticsChartActive: #baccd9d8; // sides in footer of statistic charts");
  lines.push("statisticsChartLineBlue: #327fe5; // represents blue color on statistical charts");
  lines.push("statisticsChartLineGreen: #61c752; // represents green color on statistical charts");
  lines.push("statisticsChartLineRed: #e05356; // represents red color on statistical charts");
  lines.push("statisticsChartLineGolden: #eba52d; // represents golden color on statistical charts");
  lines.push("statisticsChartLineLightblue: #58a8ed; // represents lightblue color on statistical charts");
  lines.push("statisticsChartLineLightgreen: #8fcf39; // represents lightgreen color on statistical charts");
  lines.push("statisticsChartLineOrange: #f28c39; // represents orange color on statistical charts");
  lines.push("statisticsChartLineIndigo: #7f79f3; // represents indigo color on statistical charts");
  lines.push("statisticsChartLinePurple: #9f79e8; // represents purple color on statistical charts");
  lines.push("statisticsChartLineCyan: #40d0ca; // represents cyan color on statistical charts");
  lines.push("creditsBg1: #ffb222; // credits icon gradient 1, normal");
  lines.push("creditsBg2: #ffd951; // credits icon gradient 2, light");
  lines.push("creditsBg3: #f0b400; // credits icon gradient 3, dark");
  lines.push("creditsFg: #ba7000; // credits text on light background");
  lines.push("creditsStroke: #da8735; // credits icon stroke");
  lines.push(`currencyFg: ${primary}; // currency icon, blue`);
  lines.push("rankAdminFg: #49a355; // admin badge text and pill, green");
  lines.push("rankOwnerFg: #956ac8; // owner badge text and pill, purple");
  lines.push(`rankUserFg: ${onSurfaceVariant}; // regular user badge text, gray`);

  return lines.join('\n');
}
export async function downloadDesktopTheme(colorsContent, wallpaperBlob = null, filename = 'TeleYou.tdesktop-theme') {
  const JSZip = (await import('jszip')).default;
  const zip = new JSZip();
  zip.file('colors.tdesktop-theme', colorsContent);
  if (wallpaperBlob) {
    zip.file('background.jpg', wallpaperBlob);
  } else {
    const emptyJpeg = Uint8Array.from([0xFF,0xD8,0xFF,0xE0,0x00,0x10,0x4A,0x46,0x49,0x46,0x00,0x01,
      0x01,0x00,0x00,0x01,0x00,0x01,0x00,0x00,0xFF,0xDB,0x00,0x43,0x00,0x08,0x06,0x06,
      0x07,0x06,0x05,0x08,0x07,0x07,0x07,0x09,0x09,0x08,0x0A,0x0C,0x14,0x0D,0x0C,0x0B,
      0x0B,0x0C,0x19,0x12,0x13,0x0F,0x14,0x1D,0x1A,0x1F,0x1E,0x1D,0x1A,0x1C,0x1C,0x20,
      0x24,0x2E,0x27,0x20,0x22,0x2C,0x23,0x1C,0x1C,0x28,0x37,0x29,0x2C,0x30,0x31,0x34,
      0x34,0x34,0x1F,0x27,0x39,0x3D,0x38,0x32,0x3C,0x2E,0x33,0x34,0x32,0xFF,0xC0,0x00,
      0x0B,0x08,0x00,0x01,0x00,0x01,0x01,0x01,0x11,0x00,0xFF,0xC4,0x00,0x1F,0x00,0x00,
      0x01,0x05,0x01,0x01,0x01,0x01,0x01,0x01,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
      0x01,0x02,0x03,0x04,0x05,0x06,0x07,0x08,0x09,0x0A,0x0B,0xFF,0xC4,0x00,0xB5,0x10,
      0x00,0x02,0x01,0x03,0x03,0x02,0x04,0x03,0x05,0x05,0x04,0x04,0x00,0x00,0x01,0x7D,
      0x01,0x02,0x03,0x00,0x04,0x11,0x05,0x12,0x21,0x31,0x41,0x06,0x13,0x51,0x61,0x07,
      0x22,0x71,0x14,0x32,0x81,0x91,0xA1,0x08,0x23,0x42,0xB1,0xC1,0x15,0x52,0xD1,0xF0,
      0x24,0x33,0x62,0x72,0x82,0x09,0x0A,0x16,0x17,0x18,0x19,0x1A,0x25,0x26,0x27,0x28,
      0x29,0x2A,0x34,0x35,0x36,0x37,0x38,0x39,0x3A,0x43,0x44,0x45,0x46,0x47,0x48,0x49,
      0x4A,0x53,0x54,0x55,0x56,0x57,0x58,0x59,0x5A,0x63,0x64,0x65,0x66,0x67,0x68,0x69,
      0x6A,0x73,0x74,0x75,0x76,0x77,0x78,0x79,0x7A,0x83,0x84,0x85,0x86,0x87,0x88,0x89,
      0x8A,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,
      0xA8,0xA9,0xAA,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xC2,0xC3,0xC4,0xC5,
      0xC6,0xC7,0xC8,0xC9,0xCA,0xD2,0xD3,0xD4,0xD5,0xD6,0xD7,0xD8,0xD9,0xDA,0xE1,0xE2,
      0xE3,0xE4,0xE5,0xE6,0xE7,0xE8,0xE9,0xEA,0xF1,0xF2,0xF3,0xF4,0xF5,0xF6,0xF7,0xF8,
      0xF9,0xFA,0xFF,0xDA,0x00,0x08,0x01,0x01,0x00,0x00,0x3F,0x00,0xFB,0xD5,0xBF,0xFF,0xD9]);
    zip.file('background.jpg', emptyJpeg);
  }
  const blob = await zip.generateAsync({ type: 'blob', compression: 'DEFLATE' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}